# SPDX-FileCopyrightText: 2025 Canonical Ltd
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.0
info:
  title: WebConsole NFConfig API
  version: 1.0.0
  description: API for managing access, mobility, policy, session and PLMN information.

servers:
  - url: https://localhost:5001

paths:
  /nfconfig/access-mobility:
    get:
      summary: Get Access and Mobility Configuration
      responses:
        '200':
          description: List of access and mobility configs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccessAndMobility'
        '404':
          description: Resource not found
        '500':
          description: Internal server error


  /nfconfig/plmn:
    get:
      summary: Get PLMN ID Configuration
      responses:
        '200':
          description: List of PLMN IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlmnId'
        '404':
          description: Resource not found
        '500':
          description: Internal server error

  /nfconfig/plmn-snssai:
    get:
      summary: Get PLMN-SNSSAI Configuration
      responses:
        '200':
          description: List of PLMN-SNSSAI
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlmnSnssai'
        '404':
          description: Resource not found
        '500':
          description: Internal server error

  /nfconfig/policy-control:
    get:
      summary: Get Policy Control Configuration
      responses:
        '200':
          description: List of policy control configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PolicyControl'
        '404':
          description: Resource not found
        '500':
          description: Internal server error

  /nfconfig/session-management:
    get:
      summary: Get Session Management Configuration
      responses:
        '200':
          description: List of session management configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionManagement'
        '404':
          description: Resource not found
        '500':
          description: Internal server error

components:
  schemas:
    AccessAndMobility:
      type: object
      required:
        - plmnId
        - snssai
      properties:
        plmnId:
          $ref: '#/components/schemas/PlmnId'
        snssai:
          $ref: '#/components/schemas/Snssai'
        tacs:
          type: array
          items:
            type: string

    PlmnId:
      type: object
      required:
        - mcc
        - mnc
      properties:
        mcc:
          type: string
        mnc:
          type: string

    Snssai:
      type: object
      required:
        - sst
      properties:
        sst:
          type: integer
        sd:
          type: string

    PlmnSnssai:
      type: object
      required:
        - plmnId
        - sNssaiList
      properties:
        plmnId:
          $ref: '#/components/schemas/PlmnId'
        sNssaiList:
          type: array
          items:
            $ref: '#/components/schemas/Snssai'

    PolicyControl:
      type: object
      required:
        - plmnId
        - snssai
        - pccRules
      properties:
        plmnId:
          $ref: '#/components/schemas/PlmnId'
        snssai:
          $ref: '#/components/schemas/Snssai'
        dnnQos:
          type: array
          items:
            $ref: '#/components/schemas/DnnQos'
        pccRules:
          type: array
          items:
            $ref: '#/components/schemas/PccRule'

    DnnQos:
      type: object
      required:
        - dnnName
        - mbrUplink
        - mbrDownlink
      properties:
        dnnName:
          type: string
        mbrUplink:
          type: string
        mbrDownlink:
          type: string
        fiveQi:
          type: integer
        arpPriorityLevel:
          type: integer

    PccRule:
      type: object
      required:
        - ruleId
        - flows
        - qos
        - precedence
      properties:
        ruleId:
          type: string
        flows:
          type: array
          items:
            $ref: '#/components/schemas/PccFlow'
        qos:
          $ref: '#/components/schemas/PccQos'
        precedence:
          type: integer

    PccFlow:
      type: object
      required:
        - description
        - direction
      properties:
        description:
          type: string
        direction:
          $ref: '#/components/schemas/Direction'
        status:
          $ref: '#/components/schemas/Status'

    PccQos:
      type: object
      required:
        - fiveQi
        - maxBrDl
        - maxBrUl
        - arp
      properties:
        fiveQi:
          type: integer
        maxBrUl:
          type: string
        maxBrDl:
          type: string
        arp:
          $ref: '#/components/schemas/Arp'

    Arp:
      type: object
      required:
        - priorityLevel
        - preemptCap
        - preemptVuln
      properties:
        priorityLevel:
          type: integer
        preemptCap:
          $ref: '#/components/schemas/PreemptCap'
        preemptVuln:
          $ref: '#/components/schemas/PreemptVuln'

    SessionManagement:
      type: object
      required:
        - sliceName
        - plmnId
        - snssai
      properties:
        sliceName:
          type: string
        plmnId:
          $ref: '#/components/schemas/PlmnId'
        snssai:
          $ref: '#/components/schemas/Snssai'
        ipDomain:
          type: array
          items:
            $ref: '#/components/schemas/IpDomain'
        upf:
          $ref: '#/components/schemas/Upf'
        gnbNames:
          type: array
          items:
            type: string

    IpDomain:
      type: object
      required:
        - dnnName
        - dnsIpv4
        - ueSubnet
        - mtu
      properties:
        dnnName:
          type: string
        dnsIpv4:
          type: string
        ueSubnet:
          type: string
        mtu:
          type: integer

    Upf:
      type: object
      required:
        - hostname
      properties:
        hostname:
          type: string
        port:
          type: integer

    Status:
      type: string
      enum:
        - ENABLED-UPLINK
        - ENABLED-DOWNLINK
        - ENABLED
        - DISABLED
        - REMOVED

    Direction:
      type: string
      enum:
        - DOWNLINK
        - UPLINK
        - BIDIRECTIONAL
        - UNSPECIFIED

    PreemptCap:
      type: string
      enum:
        - NOT_PREEMPT
        - MAY_PREEMPT

    PreemptVuln:
      type: string
      enum:
        - NOT_PREEMPTABLE
        - PREEMPTABLE
