/*
NRF NFManagement Service

Testing NFInstanceIDDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi_test

import (
	"context"
	"testing"

	openapiclient "github.com/omec-project/openapi/Nnrf_NFManagement"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_NFInstanceIDDocumentAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test NFInstanceIDDocumentAPIService DeregisterNFInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var nfInstanceID string

		httpRes, err := apiClient.NFInstanceIDDocumentAPI.DeregisterNFInstance(context.Background(), nfInstanceID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NFInstanceIDDocumentAPIService GetNFInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var nfInstanceID string

		resp, httpRes, err := apiClient.NFInstanceIDDocumentAPI.GetNFInstance(context.Background(), nfInstanceID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NFInstanceIDDocumentAPIService RegisterNFInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var nfInstanceID string

		resp, httpRes, err := apiClient.NFInstanceIDDocumentAPI.RegisterNFInstance(context.Background(), nfInstanceID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NFInstanceIDDocumentAPIService UpdateNFInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var nfInstanceID string

		resp, httpRes, err := apiClient.NFInstanceIDDocumentAPI.UpdateNFInstance(context.Background(), nfInstanceID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
