# Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
# Copyright 2025 Canonical Ltd.
#
# SPDX-License-Identifier: Apache-2.0
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: networkgcorefullcode/.github/.github/workflows/build.yml@main
    with:
      branch_name: ${{ github.ref }}

  # static-analysis:
  #   uses: networkgcorefullcode/.github/.github/workflows/static-analysis.yml@main
  #   with:
  #     branch_name: ${{ github.ref }}

  lint:
    uses: networkgcorefullcode/.github/.github/workflows/lint.yml@main
    with:
      branch_name: ${{ github.ref }}

  license-check:
    uses: networkgcorefullcode/.github/.github/workflows/license-check.yml@main
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: networkgcorefullcode/.github/.github/workflows/fossa-scan.yml@main
    with:
      branch_name: ${{ github.ref }}

  unit-tests:
    uses: networkgcorefullcode/.github/.github/workflows/unit-test.yml@main
    with:
      branch_name: ${{ github.ref }}
