/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// DnsSecurityProtocol DNS security protocol
type DnsSecurityProtocol string

// Unmarshal JSON data into any of the pointers in the struct
// Unmarshal JSON data into any of the pointers in the struct
func (dst *DnsSecurityProtocol) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("data failed to unmarshal into DnsSecurityProtocol: %w", err)
	}
	*dst = DnsSecurityProtocol(s)
	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *DnsSecurityProtocol) MarshalJSON() ([]byte, error) {
	if src != nil {
		return json.Marshal(string(*src))
	}

	return nil, nil // no data in anyOf schemas
}

type NullableDnsSecurityProtocol struct {
	value *DnsSecurityProtocol
	isSet bool
}

func (v NullableDnsSecurityProtocol) Get() *DnsSecurityProtocol {
	return v.value
}

func (v *NullableDnsSecurityProtocol) Set(val *DnsSecurityProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableDnsSecurityProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableDnsSecurityProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnsSecurityProtocol(val *DnsSecurityProtocol) *NullableDnsSecurityProtocol {
	return &NullableDnsSecurityProtocol{value: val, isSet: true}
}

func (v NullableDnsSecurityProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnsSecurityProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
