// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AuthenticationSubscription struct {
	AuthenticationMethod               AuthMethod      `json:"authenticationMethod" bson:"authenticationMethod"`
	PermanentKey                       *PermanentKey   `json:"permanentKey" bson:"permanentKey"`
	SequenceNumber                     string          `json:"sequenceNumber" bson:"sequenceNumber"`
	AuthenticationManagementField      string          `json:"authenticationManagementField,omitempty" bson:"authenticationManagementField"`
	VectorAlgorithm                    VectorAlgorithm `json:"vectorAlgorithm,omitempty" bson:"vectorAlgorithm"`
	Milenage                           *Milenage       `json:"milenage,omitempty" bson:"milenage"`
	Tuak                               *Tuak           `json:"tuak,omitempty" bson:"tuak"`
	Opc                                *Opc            `json:"opc,omitempty" bson:"opc"`
	Topc                               *Topc           `json:"topc,omitempty" bson:"topc"`
	SharedAuthenticationSubscriptionId *SharedData     `json:"sharedAuthenticationSubscriptionId,omitempty" bson:"sharedAuthenticationSubscriptionId"`

	// --- CAMPO AÑADIDO ---
	// El tipo []byte es para datos binarios. Las etiquetas `json` y `bson`
	// le dicen a Go cómo (de)serializar este campo desde/hacia JSON y MongoDB.
	// `omitempty` significa que el campo no se incluirá si está vacío.
	EncryptedKi []byte `json:"encryptedKi,omitempty" bson:"encryptedKi,omitempty"`
}
