/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// ImsEvent The IMS events
type ImsEvent string

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ImsEvent) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("data failed to unmarshal into ImsEvent: %w", err)
	}
	*dst = ImsEvent(s)
	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ImsEvent) MarshalJSON() ([]byte, error) {
	if src != nil {
		return json.Marshal(string(*src))
	}
	return nil, nil // no data in anyOf schemas
}

type NullableImsEvent struct {
	value *ImsEvent
	isSet bool
}

func (v NullableImsEvent) Get() *ImsEvent {
	return v.value
}

func (v *NullableImsEvent) Set(val *ImsEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableImsEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableImsEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImsEvent(val *ImsEvent) *NullableImsEvent {
	return &NullableImsEvent{value: val, isSet: true}
}

func (v NullableImsEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImsEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
