/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// N6DelayMeasurementProtocol N6 delay measurement protocol
type N6DelayMeasurementProtocol string

// Unmarshal JSON data into any of the pointers in the struct
func (dst *N6DelayMeasurementProtocol) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string)
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(N6DelayMeasurementProtocol)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *N6DelayMeasurementProtocol) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableN6DelayMeasurementProtocol struct {
	value *N6DelayMeasurementProtocol
	isSet bool
}

func (v NullableN6DelayMeasurementProtocol) Get() *N6DelayMeasurementProtocol {
	return v.value
}

func (v *NullableN6DelayMeasurementProtocol) Set(val *N6DelayMeasurementProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableN6DelayMeasurementProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableN6DelayMeasurementProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableN6DelayMeasurementProtocol(val *N6DelayMeasurementProtocol) *NullableN6DelayMeasurementProtocol {
	return &NullableN6DelayMeasurementProtocol{value: val, isSet: true}
}

func (v NullableN6DelayMeasurementProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableN6DelayMeasurementProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
