/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// N6DelayMeasurementProtocol N6 delay measurement protocol
type N6DelayMeasurementProtocol string

// Unmarshal JSON data into any of the pointers in the struct
func (dst *N6DelayMeasurementProtocol) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("N6DelayMeasurementProtocol should be a string, got %s", string(data))
	}
	*dst = N6DelayMeasurementProtocol(s)
	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src N6DelayMeasurementProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(src))
}

type NullableN6DelayMeasurementProtocol struct {
	value *N6DelayMeasurementProtocol
	isSet bool
}

func (v NullableN6DelayMeasurementProtocol) Get() *N6DelayMeasurementProtocol {
	return v.value
}

func (v *NullableN6DelayMeasurementProtocol) Set(val *N6DelayMeasurementProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableN6DelayMeasurementProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableN6DelayMeasurementProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableN6DelayMeasurementProtocol(val *N6DelayMeasurementProtocol) *NullableN6DelayMeasurementProtocol {
	return &NullableN6DelayMeasurementProtocol{value: val, isSet: true}
}

func (v NullableN6DelayMeasurementProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableN6DelayMeasurementProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
