/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// N32Purpose Usage purpose of establishing N32 connectivity
type N32Purpose string

// Unmarshal JSON data into any of the pointers in the struct
func (dst *N32Purpose) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("data failed to unmarshal into N32Purpose: %w", err)
	}
	*dst = N32Purpose(s)
	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *N32Purpose) MarshalJSON() ([]byte, error) {
	if src != nil {
		return json.Marshal(string(*src))
	}
	return nil, nil // no data in anyOf schemas
}

type NullableN32Purpose struct {
	value *N32Purpose
	isSet bool
}

func (v NullableN32Purpose) Get() *N32Purpose {
	return v.value
}

func (v *NullableN32Purpose) Set(val *N32Purpose) {
	v.value = val
	v.isSet = true
}

func (v NullableN32Purpose) IsSet() bool {
	return v.isSet
}

func (v *NullableN32Purpose) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableN32Purpose(val *N32Purpose) *NullableN32Purpose {
	return &NullableN32Purpose{value: val, isSet: true}
}

func (v NullableN32Purpose) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableN32Purpose) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
