/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// VflCapabilityType Type of Vertical Federated Learning Capability
type VflCapabilityType struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *VflCapabilityType) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string)
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(VflCapabilityType)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *VflCapabilityType) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableVflCapabilityType struct {
	value *VflCapabilityType
	isSet bool
}

func (v NullableVflCapabilityType) Get() *VflCapabilityType {
	return v.value
}

func (v *NullableVflCapabilityType) Set(val *VflCapabilityType) {
	v.value = val
	v.isSet = true
}

func (v NullableVflCapabilityType) IsSet() bool {
	return v.isSet
}

func (v *NullableVflCapabilityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVflCapabilityType(val *VflCapabilityType) *NullableVflCapabilityType {
	return &NullableVflCapabilityType{value: val, isSet: true}
}

func (v NullableVflCapabilityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVflCapabilityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
