// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * NRF NFManagement Service
 *
 * Ipv6Addr type definition
 *
 * API version: 1.4.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Ipv6Addr represents an IPv6 address
type Ipv6Addr struct {
	Value string `json:"value,omitempty" yaml:"value" bson:"value" mapstructure:"Value"`
}
