/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the N2InterfaceAmfInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &N2InterfaceAmfInfo{}

// N2InterfaceAmfInfo AMF N2 interface information
type N2InterfaceAmfInfo struct {
	Ipv4EndpointAddress []string   `json:"ipv4EndpointAddress,omitempty"`
	Ipv6EndpointAddress []Ipv6Addr `json:"ipv6EndpointAddress,omitempty"`
	// Fully Qualified Domain Name
	AmfName *string `json:"amfName,omitempty"`
}

// NewN2InterfaceAmfInfo instantiates a new N2InterfaceAmfInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewN2InterfaceAmfInfo() *N2InterfaceAmfInfo {
	this := N2InterfaceAmfInfo{}
	return &this
}

// NewN2InterfaceAmfInfoWithDefaults instantiates a new N2InterfaceAmfInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewN2InterfaceAmfInfoWithDefaults() *N2InterfaceAmfInfo {
	this := N2InterfaceAmfInfo{}
	return &this
}

// GetIpv4EndpointAddress returns the Ipv4EndpointAddress field value if set, zero value otherwise.
func (o *N2InterfaceAmfInfo) GetIpv4EndpointAddress() []string {
	if o == nil || IsNil(o.Ipv4EndpointAddress) {
		var ret []string
		return ret
	}
	return o.Ipv4EndpointAddress
}

// GetIpv4EndpointAddressOk returns a tuple with the Ipv4EndpointAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *N2InterfaceAmfInfo) GetIpv4EndpointAddressOk() ([]string, bool) {
	if o == nil || IsNil(o.Ipv4EndpointAddress) {
		return nil, false
	}
	return o.Ipv4EndpointAddress, true
}

// HasIpv4EndpointAddress returns a boolean if a field has been set.
func (o *N2InterfaceAmfInfo) HasIpv4EndpointAddress() bool {
	if o != nil && !IsNil(o.Ipv4EndpointAddress) {
		return true
	}

	return false
}

// SetIpv4EndpointAddress gets a reference to the given []string and assigns it to the Ipv4EndpointAddress field.
func (o *N2InterfaceAmfInfo) SetIpv4EndpointAddress(v []string) {
	o.Ipv4EndpointAddress = v
}

// GetIpv6EndpointAddress returns the Ipv6EndpointAddress field value if set, zero value otherwise.
func (o *N2InterfaceAmfInfo) GetIpv6EndpointAddress() []Ipv6Addr {
	if o == nil || IsNil(o.Ipv6EndpointAddress) {
		var ret []Ipv6Addr
		return ret
	}
	return o.Ipv6EndpointAddress
}

// GetIpv6EndpointAddressOk returns a tuple with the Ipv6EndpointAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *N2InterfaceAmfInfo) GetIpv6EndpointAddressOk() ([]Ipv6Addr, bool) {
	if o == nil || IsNil(o.Ipv6EndpointAddress) {
		return nil, false
	}
	return o.Ipv6EndpointAddress, true
}

// HasIpv6EndpointAddress returns a boolean if a field has been set.
func (o *N2InterfaceAmfInfo) HasIpv6EndpointAddress() bool {
	if o != nil && !IsNil(o.Ipv6EndpointAddress) {
		return true
	}

	return false
}

// SetIpv6EndpointAddress gets a reference to the given []Ipv6Addr and assigns it to the Ipv6EndpointAddress field.
func (o *N2InterfaceAmfInfo) SetIpv6EndpointAddress(v []Ipv6Addr) {
	o.Ipv6EndpointAddress = v
}

// GetAmfName returns the AmfName field value if set, zero value otherwise.
func (o *N2InterfaceAmfInfo) GetAmfName() string {
	if o == nil || IsNil(o.AmfName) {
		var ret string
		return ret
	}
	return *o.AmfName
}

// GetAmfNameOk returns a tuple with the AmfName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *N2InterfaceAmfInfo) GetAmfNameOk() (*string, bool) {
	if o == nil || IsNil(o.AmfName) {
		return nil, false
	}
	return o.AmfName, true
}

// HasAmfName returns a boolean if a field has been set.
func (o *N2InterfaceAmfInfo) HasAmfName() bool {
	if o != nil && !IsNil(o.AmfName) {
		return true
	}

	return false
}

// SetAmfName gets a reference to the given string and assigns it to the AmfName field.
func (o *N2InterfaceAmfInfo) SetAmfName(v string) {
	o.AmfName = &v
}

func (o N2InterfaceAmfInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o N2InterfaceAmfInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ipv4EndpointAddress) {
		toSerialize["ipv4EndpointAddress"] = o.Ipv4EndpointAddress
	}
	if !IsNil(o.Ipv6EndpointAddress) {
		toSerialize["ipv6EndpointAddress"] = o.Ipv6EndpointAddress
	}
	if !IsNil(o.AmfName) {
		toSerialize["amfName"] = o.AmfName
	}
	return toSerialize, nil
}

type NullableN2InterfaceAmfInfo struct {
	value *N2InterfaceAmfInfo
	isSet bool
}

func (v NullableN2InterfaceAmfInfo) Get() *N2InterfaceAmfInfo {
	return v.value
}

func (v *NullableN2InterfaceAmfInfo) Set(val *N2InterfaceAmfInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableN2InterfaceAmfInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableN2InterfaceAmfInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableN2InterfaceAmfInfo(val *N2InterfaceAmfInfo) *NullableN2InterfaceAmfInfo {
	return &NullableN2InterfaceAmfInfo{value: val, isSet: true}
}

func (v NullableN2InterfaceAmfInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableN2InterfaceAmfInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
