/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DnnMbSmfInfoItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DnnMbSmfInfoItem{}

// DnnMbSmfInfoItem Parameters supported by an MB-SMF for a given DNN
type DnnMbSmfInfoItem struct {
	Dnn DnnSmfInfoItemDnn `json:"dnn"`
}

type _DnnMbSmfInfoItem DnnMbSmfInfoItem

// NewDnnMbSmfInfoItem instantiates a new DnnMbSmfInfoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnnMbSmfInfoItem(dnn DnnSmfInfoItemDnn) *DnnMbSmfInfoItem {
	this := DnnMbSmfInfoItem{}
	this.Dnn = dnn
	return &this
}

// NewDnnMbSmfInfoItemWithDefaults instantiates a new DnnMbSmfInfoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnnMbSmfInfoItemWithDefaults() *DnnMbSmfInfoItem {
	this := DnnMbSmfInfoItem{}
	return &this
}

// GetDnn returns the Dnn field value
func (o *DnnMbSmfInfoItem) GetDnn() DnnSmfInfoItemDnn {
	if o == nil {
		var ret DnnSmfInfoItemDnn
		return ret
	}

	return o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value
// and a boolean to check if the value has been set.
func (o *DnnMbSmfInfoItem) GetDnnOk() (*DnnSmfInfoItemDnn, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dnn, true
}

// SetDnn sets field value
func (o *DnnMbSmfInfoItem) SetDnn(v DnnSmfInfoItemDnn) {
	o.Dnn = v
}

func (o DnnMbSmfInfoItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DnnMbSmfInfoItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dnn"] = o.Dnn
	return toSerialize, nil
}

func (o *DnnMbSmfInfoItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dnn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDnnMbSmfInfoItem := _DnnMbSmfInfoItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDnnMbSmfInfoItem)

	if err != nil {
		return err
	}

	*o = DnnMbSmfInfoItem(varDnnMbSmfInfoItem)

	return err
}

type NullableDnnMbSmfInfoItem struct {
	value *DnnMbSmfInfoItem
	isSet bool
}

func (v NullableDnnMbSmfInfoItem) Get() *DnnMbSmfInfoItem {
	return v.value
}

func (v *NullableDnnMbSmfInfoItem) Set(val *DnnMbSmfInfoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDnnMbSmfInfoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDnnMbSmfInfoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnnMbSmfInfoItem(val *DnnMbSmfInfoItem) *NullableDnnMbSmfInfoItem {
	return &NullableDnnMbSmfInfoItem{value: val, isSet: true}
}

func (v NullableDnnMbSmfInfoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnnMbSmfInfoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
