/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// SupportedGADShapes Indicates supported GAD shapes.
type SupportedGADShapes string

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SupportedGADShapes) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	var s string
	err = json.Unmarshal(data, &s)
	if err == nil {
		*dst = SupportedGADShapes(s)
		return nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SupportedGADShapes)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *SupportedGADShapes) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(*src))
}

type NullableSupportedGADShapes struct {
	value *SupportedGADShapes
	isSet bool
}

func (v NullableSupportedGADShapes) Get() *SupportedGADShapes {
	return v.value
}

func (v *NullableSupportedGADShapes) Set(val *SupportedGADShapes) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedGADShapes) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedGADShapes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedGADShapes(val *SupportedGADShapes) *NullableSupportedGADShapes {
	return &NullableSupportedGADShapes{value: val, isSet: true}
}

func (v NullableSupportedGADShapes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedGADShapes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
