/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the PruExistenceInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PruExistenceInfo{}

// PruExistenceInfo PRU Existence Information
type PruExistenceInfo struct {
	TaiList      []Tai      `json:"taiList,omitempty"`
	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`
}

// NewPruExistenceInfo instantiates a new PruExistenceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPruExistenceInfo() *PruExistenceInfo {
	this := PruExistenceInfo{}
	return &this
}

// NewPruExistenceInfoWithDefaults instantiates a new PruExistenceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPruExistenceInfoWithDefaults() *PruExistenceInfo {
	this := PruExistenceInfo{}
	return &this
}

// GetTaiList returns the TaiList field value if set, zero value otherwise.
func (o *PruExistenceInfo) GetTaiList() []Tai {
	if o == nil || IsNil(o.TaiList) {
		var ret []Tai
		return ret
	}
	return o.TaiList
}

// GetTaiListOk returns a tuple with the TaiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PruExistenceInfo) GetTaiListOk() ([]Tai, bool) {
	if o == nil || IsNil(o.TaiList) {
		return nil, false
	}
	return o.TaiList, true
}

// HasTaiList returns a boolean if a field has been set.
func (o *PruExistenceInfo) HasTaiList() bool {
	if o != nil && !IsNil(o.TaiList) {
		return true
	}

	return false
}

// SetTaiList gets a reference to the given []Tai and assigns it to the TaiList field.
func (o *PruExistenceInfo) SetTaiList(v []Tai) {
	o.TaiList = v
}

// GetTaiRangeList returns the TaiRangeList field value if set, zero value otherwise.
func (o *PruExistenceInfo) GetTaiRangeList() []TaiRange {
	if o == nil || IsNil(o.TaiRangeList) {
		var ret []TaiRange
		return ret
	}
	return o.TaiRangeList
}

// GetTaiRangeListOk returns a tuple with the TaiRangeList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PruExistenceInfo) GetTaiRangeListOk() ([]TaiRange, bool) {
	if o == nil || IsNil(o.TaiRangeList) {
		return nil, false
	}
	return o.TaiRangeList, true
}

// HasTaiRangeList returns a boolean if a field has been set.
func (o *PruExistenceInfo) HasTaiRangeList() bool {
	if o != nil && !IsNil(o.TaiRangeList) {
		return true
	}

	return false
}

// SetTaiRangeList gets a reference to the given []TaiRange and assigns it to the TaiRangeList field.
func (o *PruExistenceInfo) SetTaiRangeList(v []TaiRange) {
	o.TaiRangeList = v
}

func (o PruExistenceInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PruExistenceInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaiList) {
		toSerialize["taiList"] = o.TaiList
	}
	if !IsNil(o.TaiRangeList) {
		toSerialize["taiRangeList"] = o.TaiRangeList
	}
	return toSerialize, nil
}

type NullablePruExistenceInfo struct {
	value *PruExistenceInfo
	isSet bool
}

func (v NullablePruExistenceInfo) Get() *PruExistenceInfo {
	return v.value
}

func (v *NullablePruExistenceInfo) Set(val *PruExistenceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePruExistenceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePruExistenceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePruExistenceInfo(val *PruExistenceInfo) *NullablePruExistenceInfo {
	return &NullablePruExistenceInfo{value: val, isSet: true}
}

func (v NullablePruExistenceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePruExistenceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
