// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * NRF NFManagement Service
 *
 * UdsfInfo type definition
 *
 * API version: 1.4.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// UdsfInfo Information of an UDSF NF Instance
type UdsfInfo struct {
	GroupId                        *string          `json:"groupId,omitempty" yaml:"groupId" bson:"groupId" mapstructure:"GroupId"`
	SupiRanges                     []SupiRange      `json:"supiRanges,omitempty" yaml:"supiRanges" bson:"supiRanges" mapstructure:"SupiRanges"`
	GpsiRanges                     []IdentityRange  `json:"gpsiRanges,omitempty" yaml:"gpsiRanges" bson:"gpsiRanges" mapstructure:"GpsiRanges"`
	ExternalGroupIdentifiersRanges []IdentityRange  `json:"externalGroupIdentifiersRanges,omitempty" yaml:"externalGroupIdentifiersRanges" bson:"externalGroupIdentifiersRanges" mapstructure:"ExternalGroupIdentifiersRanges"`
	StorageIdRanges                []StorageIdRange `json:"storageIdRanges,omitempty" yaml:"storageIdRanges" bson:"storageIdRanges" mapstructure:"StorageIdRanges"`
}
