/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RoutingAreaIdRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingAreaIdRange{}

// RoutingAreaIdRange Routing Area ID Range.
type RoutingAreaIdRange struct {
	PlmnId   PlmnId `json:"plmnId"`
	StartLac string `json:"startLac"`
	EndLac   string `json:"endLac"`
	StartRac string `json:"startRac"`
	EndRac   string `json:"endRac"`
}

type _RoutingAreaIdRange RoutingAreaIdRange

// NewRoutingAreaIdRange instantiates a new RoutingAreaIdRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingAreaIdRange(plmnId PlmnId, startLac string, endLac string, startRac string, endRac string) *RoutingAreaIdRange {
	this := RoutingAreaIdRange{}
	this.PlmnId = plmnId
	this.StartLac = startLac
	this.EndLac = endLac
	this.StartRac = startRac
	this.EndRac = endRac
	return &this
}

// NewRoutingAreaIdRangeWithDefaults instantiates a new RoutingAreaIdRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingAreaIdRangeWithDefaults() *RoutingAreaIdRange {
	this := RoutingAreaIdRange{}
	return &this
}

// GetPlmnId returns the PlmnId field value
func (o *RoutingAreaIdRange) GetPlmnId() PlmnId {
	if o == nil {
		var ret PlmnId
		return ret
	}

	return o.PlmnId
}

// GetPlmnIdOk returns a tuple with the PlmnId field value
// and a boolean to check if the value has been set.
func (o *RoutingAreaIdRange) GetPlmnIdOk() (*PlmnId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlmnId, true
}

// SetPlmnId sets field value
func (o *RoutingAreaIdRange) SetPlmnId(v PlmnId) {
	o.PlmnId = v
}

// GetStartLac returns the StartLac field value
func (o *RoutingAreaIdRange) GetStartLac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartLac
}

// GetStartLacOk returns a tuple with the StartLac field value
// and a boolean to check if the value has been set.
func (o *RoutingAreaIdRange) GetStartLacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartLac, true
}

// SetStartLac sets field value
func (o *RoutingAreaIdRange) SetStartLac(v string) {
	o.StartLac = v
}

// GetEndLac returns the EndLac field value
func (o *RoutingAreaIdRange) GetEndLac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndLac
}

// GetEndLacOk returns a tuple with the EndLac field value
// and a boolean to check if the value has been set.
func (o *RoutingAreaIdRange) GetEndLacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndLac, true
}

// SetEndLac sets field value
func (o *RoutingAreaIdRange) SetEndLac(v string) {
	o.EndLac = v
}

// GetStartRac returns the StartRac field value
func (o *RoutingAreaIdRange) GetStartRac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartRac
}

// GetStartRacOk returns a tuple with the StartRac field value
// and a boolean to check if the value has been set.
func (o *RoutingAreaIdRange) GetStartRacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartRac, true
}

// SetStartRac sets field value
func (o *RoutingAreaIdRange) SetStartRac(v string) {
	o.StartRac = v
}

// GetEndRac returns the EndRac field value
func (o *RoutingAreaIdRange) GetEndRac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndRac
}

// GetEndRacOk returns a tuple with the EndRac field value
// and a boolean to check if the value has been set.
func (o *RoutingAreaIdRange) GetEndRacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndRac, true
}

// SetEndRac sets field value
func (o *RoutingAreaIdRange) SetEndRac(v string) {
	o.EndRac = v
}

func (o RoutingAreaIdRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingAreaIdRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plmnId"] = o.PlmnId
	toSerialize["startLac"] = o.StartLac
	toSerialize["endLac"] = o.EndLac
	toSerialize["startRac"] = o.StartRac
	toSerialize["endRac"] = o.EndRac
	return toSerialize, nil
}

func (o *RoutingAreaIdRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plmnId",
		"startLac",
		"endLac",
		"startRac",
		"endRac",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingAreaIdRange := _RoutingAreaIdRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoutingAreaIdRange)

	if err != nil {
		return err
	}

	*o = RoutingAreaIdRange(varRoutingAreaIdRange)

	return err
}

type NullableRoutingAreaIdRange struct {
	value *RoutingAreaIdRange
	isSet bool
}

func (v NullableRoutingAreaIdRange) Get() *RoutingAreaIdRange {
	return v.value
}

func (v *NullableRoutingAreaIdRange) Set(val *RoutingAreaIdRange) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingAreaIdRange) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingAreaIdRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingAreaIdRange(val *RoutingAreaIdRange) *NullableRoutingAreaIdRange {
	return &NullableRoutingAreaIdRange{value: val, isSet: true}
}

func (v NullableRoutingAreaIdRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingAreaIdRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
