// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * NRF NFManagement Service
 *
 * NefInfo type definition
 *
 * API version: 1.4.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// NefInfo Information of an NEF NF Instance
type NefInfo struct {
	// Identity of the NEF
	NefId *string `json:"nefId,omitempty" yaml:"nefId" bson:"nefId" mapstructure:"NefId"`
	// PfdData is already defined in the project, so we'll reference it without redeclaring
	GpsiRanges                     []IdentityRange `json:"gpsiRanges,omitempty" yaml:"gpsiRanges" bson:"gpsiRanges" mapstructure:"GpsiRanges"`
	ExternalGroupIdentifiersRanges []IdentityRange `json:"externalGroupIdentifiersRanges,omitempty" yaml:"externalGroupIdentifiersRanges" bson:"externalGroupIdentifiersRanges" mapstructure:"ExternalGroupIdentifiersRanges"`
	ServedFqdnList                 []string        `json:"servedFqdnList,omitempty" yaml:"servedFqdnList" bson:"servedFqdnList" mapstructure:"ServedFqdnList"`
	TaiList                        []Tai           `json:"taiList,omitempty" yaml:"taiList" bson:"taiList" mapstructure:"TaiList"`
	TaiRangeList                   []TaiRange      `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList" mapstructure:"TaiRangeList"`
	DnaiList                       []string        `json:"dnaiList,omitempty" yaml:"dnaiList" bson:"dnaiList" mapstructure:"DnaiList"`
	UnTrustAfInfoList              []UnTrustAfInfo `json:"unTrustAfInfoList,omitempty" yaml:"unTrustAfInfoList" bson:"unTrustAfInfoList" mapstructure:"UnTrustAfInfoList"`
	UasNfFunctionalityInd          *bool           `json:"uasNfFunctionalityInd,omitempty" yaml:"uasNfFunctionalityInd" bson:"uasNfFunctionalityInd" mapstructure:"UasNfFunctionalityInd"`
	MultiMemAfSessQosInd           *bool           `json:"multiMemAfSessQosInd,omitempty" yaml:"multiMemAfSessQosInd" bson:"multiMemAfSessQosInd" mapstructure:"MultiMemAfSessQosInd"`
	MemberUESelAssistInd           *bool           `json:"memberUESelAssistInd,omitempty" yaml:"memberUESelAssistInd" bson:"memberUESelAssistInd" mapstructure:"MemberUESelAssistInd"`
}
