/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// UpfPacketInspectionFunctionality Indicates a packet inspection functionality of the UPF.
type UpfPacketInspectionFunctionality struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpfPacketInspectionFunctionality) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string)
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(UpfPacketInspectionFunctionality)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *UpfPacketInspectionFunctionality) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableUpfPacketInspectionFunctionality struct {
	value *UpfPacketInspectionFunctionality
	isSet bool
}

func (v NullableUpfPacketInspectionFunctionality) Get() *UpfPacketInspectionFunctionality {
	return v.value
}

func (v *NullableUpfPacketInspectionFunctionality) Set(val *UpfPacketInspectionFunctionality) {
	v.value = val
	v.isSet = true
}

func (v NullableUpfPacketInspectionFunctionality) IsSet() bool {
	return v.isSet
}

func (v *NullableUpfPacketInspectionFunctionality) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpfPacketInspectionFunctionality(val *UpfPacketInspectionFunctionality) *NullableUpfPacketInspectionFunctionality {
	return &NullableUpfPacketInspectionFunctionality{value: val, isSet: true}
}

func (v NullableUpfPacketInspectionFunctionality) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpfPacketInspectionFunctionality) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
