// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * NRF NFManagement Service
 *
 * NwdafInfo type definition
 *
 * API version: 1.4.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// NwdafInfo Information of an NWDAF NF Instance
type NwdafInfo struct {
	EventIds           []EventId         `json:"eventIds,omitempty" yaml:"eventIds" bson:"eventIds" mapstructure:"EventIds"`
	NwdafEvents        []NwdafEvent      `json:"nwdafEvents,omitempty" yaml:"nwdafEvents" bson:"nwdafEvents" mapstructure:"NwdafEvents"`
	TaiList            []Tai             `json:"taiList,omitempty" yaml:"taiList" bson:"taiList" mapstructure:"TaiList"`
	TaiRangeList       []TaiRange        `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList" mapstructure:"TaiRangeList"`
	NwdafCapability    *NwdafCapability  `json:"nwdafCapability,omitempty" yaml:"nwdafCapability" bson:"nwdafCapability" mapstructure:"NwdafCapability"`
	AnalyticsDelay     *int32            `json:"analyticsDelay,omitempty" yaml:"analyticsDelay" bson:"analyticsDelay" mapstructure:"AnalyticsDelay"`
	ServingNfSetIdList []string          `json:"servingNfSetIdList,omitempty" yaml:"servingNfSetIdList" bson:"servingNfSetIdList" mapstructure:"ServingNfSetIdList"`
	ServingNfTypeList  []NfType          `json:"servingNfTypeList,omitempty" yaml:"servingNfTypeList" bson:"servingNfTypeList" mapstructure:"ServingNfTypeList"`
	MlAnalyticsList    []MlAnalyticsInfo `json:"mlAnalyticsList,omitempty" yaml:"mlAnalyticsList" bson:"mlAnalyticsList" mapstructure:"MlAnalyticsList"`
}
