// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * NRF NFManagement Service
 *
 * RuleSetAction type definition
 *
 * API version: 1.4.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// RuleSetAction represents the action to be taken for a rule set
type RuleSetAction struct {
	Value string `json:"value" yaml:"value" bson:"value" mapstructure:"Value"`
}
