/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// DnnSmfInfoItemDnaiListInner struct for DnnSmfInfoItemDnaiListInner
type DnnSmfInfoItemDnaiListInner string

// Unmarshal JSON data into any of the pointers in the struct
func (dst *DnnSmfInfoItemDnaiListInner) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("data failed to unmarshal into DnnSmfInfoItemDnaiListInner: %w", err)
	}
	*dst = DnnSmfInfoItemDnaiListInner(s)
	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *DnnSmfInfoItemDnaiListInner) MarshalJSON() ([]byte, error) {
	if src != nil {
		return json.Marshal(string(*src))
	}

	return nil, nil // no data in anyOf schemas
}

type NullableDnnSmfInfoItemDnaiListInner struct {
	value *DnnSmfInfoItemDnaiListInner
	isSet bool
}

func (v NullableDnnSmfInfoItemDnaiListInner) Get() *DnnSmfInfoItemDnaiListInner {
	return v.value
}

func (v *NullableDnnSmfInfoItemDnaiListInner) Set(val *DnnSmfInfoItemDnaiListInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDnnSmfInfoItemDnaiListInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDnnSmfInfoItemDnaiListInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnnSmfInfoItemDnaiListInner(val *DnnSmfInfoItemDnaiListInner) *NullableDnnSmfInfoItemDnaiListInner {
	return &NullableDnnSmfInfoItemDnaiListInner{value: val, isSet: true}
}

func (v NullableDnnSmfInfoItemDnaiListInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnnSmfInfoItemDnaiListInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
