// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type NfProfile struct {
	NfInstanceId                            string                              `json:"nfInstanceId" yaml:"nfInstanceId" bson:"nfInstanceId" mapstructure:"NfInstanceId"`
	NfInstanceName                          string                              `json:"nfInstanceName,omitempty"`
	NfType                                  NfType                              `json:"nfType" yaml:"nfType" bson:"nfType" mapstructure:"NfType"`
	NfStatus                                NfStatus                            `json:"nfStatus" yaml:"nfStatus" bson:"nfStatus" mapstructure:"NfStatus"`
	CollocatedNfInstances                   []CollocatedNfInstance              `json:"collocatedNfInstances,omitempty"`
	HeartBeatTimer                          int32                               `json:"heartBeatTimer,omitempty" yaml:"heartBeatTimer" bson:"heartBeatTimer" mapstructure:"HeartBeatTimer"`
	PlmnList                                *[]PlmnId                           `json:"plmnList,omitempty" yaml:"plmnList" bson:"plmnList" mapstructure:"PlmnList"`
	SnpnList                                []PlmnIdNid                         `json:"snpnList,omitempty"`
	SNssais                                 *[]Snssai                           `json:"sNssais,omitempty" yaml:"sNssais" bson:"sNssais" mapstructure:"SNssais"`
	PerPlmnSnssaiList                       []PlmnSnssai                        `json:"perPlmnSnssaiList,omitempty" yaml:"perPlmnSnssaiList" bson:"perPlmnSnssaiList" mapstructure:"PerPlmnSnssaiList"`
	NsiList                                 []string                            `json:"nsiList,omitempty" yaml:"nsiList" bson:"nsiList" mapstructure:"NsiList"`
	Fqdn                                    string                              `json:"fqdn,omitempty" yaml:"fqdn" bson:"fqdn" mapstructure:"Fqdn"`
	InterPlmnFqdn                           string                              `json:"interPlmnFqdn,omitempty" yaml:"interPlmnFqdn" bson:"interPlmnFqdn" mapstructure:"InterPlmnFqdn"`
	Ipv4Addresses                           []string                            `json:"ipv4Addresses,omitempty" yaml:"ipv4Addresses" bson:"ipv4Addresses" mapstructure:"Ipv4Addresses"`
	Ipv6Addresses                           []string                            `json:"ipv6Addresses,omitempty" yaml:"ipv6Addresses" bson:"ipv6Addresses" mapstructure:"Ipv6Addresses"`
	AllowedPlmns                            *[]PlmnId                           `json:"allowedPlmns,omitempty" yaml:"allowedPlmns" bson:"allowedPlmns" mapstructure:"AllowedPlmns"`
	AllowedSnpns                            []PlmnIdNid                         `json:"allowedSnpns,omitempty"`
	AllowedNfTypes                          []NfType                            `json:"allowedNfTypes,omitempty" yaml:"allowedNfTypes" bson:"allowedNfTypes" mapstructure:"AllowedNfTypes"`
	AllowedNfDomains                        []string                            `json:"allowedNfDomains,omitempty" yaml:"allowedNfDomains" bson:"allowedNfDomains" mapstructure:"AllowedNfDomains"`
	AllowedNssais                           *[]Snssai                           `json:"allowedNssais,omitempty" yaml:"allowedNssais" bson:"allowedNssais" mapstructure:"AllowedNssais"`
	AllowedRuleSet                          *map[string]RuleSet                 `json:"allowedRuleSet,omitempty" yaml:"allowedRuleSet" bson:"allowedRuleSet" mapstructure:"AllowedRuleSet"`
	Priority                                int32                               `json:"priority,omitempty" yaml:"priority" bson:"priority" mapstructure:"Priority"`
	Capacity                                int32                               `json:"capacity,omitempty" yaml:"capacity" bson:"capacity" mapstructure:"Capacity"`
	Load                                    int32                               `json:"load,omitempty" yaml:"load" bson:"load" mapstructure:"Load"`
	LoadTimeStamp                           *time.Time                          `json:"loadTimeStamp,omitempty"`
	Locality                                string                              `json:"locality,omitempty" yaml:"locality" bson:"locality" mapstructure:"Locality"`
	ExtLocality                             *map[string]string                  `json:"extLocality,omitempty" yaml:"extLocality" bson:"extLocality" mapstructure:"ExtLocality"`
	UdrInfo                                 *UdrInfo                            `json:"udrInfo,omitempty" yaml:"udrInfo" bson:"udrInfo" mapstructure:"UdrInfo"`
	UdrInfoList                             *map[string]UdrInfo                 `json:"udrInfoList,omitempty" yaml:"udrInfoList" bson:"udrInfoList" mapstructure:"UdrInfoList"`
	UdmInfo                                 *UdmInfo                            `json:"udmInfo,omitempty" yaml:"udmInfo" bson:"udmInfo" mapstructure:"UdmInfo"`
	UdmInfoList                             *map[string]UdmInfo                 `json:"udmInfoList,omitempty" yaml:"udmInfoList" bson:"udmInfoList" mapstructure:"UdmInfoList"`
	AusfInfo                                *AusfInfo                           `json:"ausfInfo,omitempty" yaml:"ausfInfo" bson:"ausfInfo" mapstructure:"AusfInfo"`
	AusfInfoList                            *map[string]AusfInfo                `json:"ausfInfoList,omitempty" yaml:"ausfInfoList" bson:"ausfInfoList" mapstructure:"AusfInfoList"`
	AmfInfo                                 *AmfInfo                            `json:"amfInfo,omitempty" yaml:"amfInfo" bson:"amfInfo" mapstructure:"AmfInfo"`
	AmfInfoList                             *map[string]AmfInfo                 `json:"amfInfoList,omitempty" yaml:"amfInfoList" bson:"amfInfoList" mapstructure:"AmfInfoList"`
	SmfInfo                                 *SmfInfo                            `json:"smfInfo,omitempty" yaml:"smfInfo" bson:"smfInfo" mapstructure:"SmfInfo"`
	SmfInfoList                             *map[string]SmfInfo                 `json:"smfInfoList,omitempty" yaml:"smfInfoList" bson:"smfInfoList" mapstructure:"SmfInfoList"`
	UpfInfo                                 *UpfInfo                            `json:"upfInfo,omitempty" yaml:"upfInfo" bson:"upfInfo" mapstructure:"UpfInfo"`
	UpfInfoList                             *map[string]UpfInfo                 `json:"upfInfoList,omitempty" yaml:"upfInfoList" bson:"upfInfoList" mapstructure:"UpfInfoList"`
	PcfInfo                                 *PcfInfo                            `json:"pcfInfo,omitempty" yaml:"pcfInfo" bson:"pcfInfo" mapstructure:"PcfInfo"`
	PcfInfoList                             *map[string]PcfInfo                 `json:"pcfInfoList,omitempty" yaml:"pcfInfoList" bson:"pcfInfoList" mapstructure:"PcfInfoList"`
	BsfInfo                                 *BsfInfo                            `json:"bsfInfo,omitempty" yaml:"bsfInfo" bson:"bsfInfo" mapstructure:"BsfInfo"`
	BsfInfoList                             *map[string]BsfInfo                 `json:"bsfInfoList,omitempty" yaml:"bsfInfoList" bson:"bsfInfoList" mapstructure:"BsfInfoList"`
	ChfInfo                                 *ChfInfo                            `json:"chfInfo,omitempty" yaml:"chfInfo" bson:"chfInfo" mapstructure:"ChfInfo"`
	ChfInfoList                             *map[string]ChfInfo                 `json:"chfInfoList,omitempty" yaml:"chfInfoList" bson:"chfInfoList" mapstructure:"ChfInfoList"`
	NefInfo                                 *NefInfo                            `json:"nefInfo,omitempty" yaml:"nefInfo" bson:"nefInfo" mapstructure:"NefInfo"`
	NrfInfo                                 *NrfInfo                            `json:"nrfInfo,omitempty" yaml:"nrfInfo" bson:"nrfInfo" mapstructure:"NrfInfo"`
	UdsfInfo                                *UdsfInfo                           `json:"udsfInfo,omitempty" yaml:"udsfInfo" bson:"udsfInfo" mapstructure:"UdsfInfo"`
	UdsfInfoList                            *map[string]UdsfInfo                `json:"udsfInfoList,omitempty" yaml:"udsfInfoList" bson:"udsfInfoList" mapstructure:"UdsfInfoList"`
	NwdafInfo                               *NwdafInfo                          `json:"nwdafInfo,omitempty" yaml:"nwdafInfo" bson:"nwdafInfo" mapstructure:"NwdafInfo"`
	NwdafInfoList                           *map[string]NwdafInfo               `json:"nwdafInfoList,omitempty" yaml:"nwdafInfoList" bson:"nwdafInfoList" mapstructure:"NwdafInfoList"`
	PcscfInfoList                           *map[string]PcscfInfo               `json:"pcscfInfoList,omitempty" yaml:"pcscfInfoList" bson:"pcscfInfoList" mapstructure:"PcscfInfoList"`
	HssInfoList                             *map[string]HssInfo                 `json:"hssInfoList,omitempty" yaml:"hssInfoList" bson:"hssInfoList" mapstructure:"HssInfoList"`
	CustomInfo                              map[string]interface{}              `json:"customInfo,omitempty" yaml:"customInfo" bson:"customInfo" mapstructure:"CustomInfo"`
	RecoveryTime                            *time.Time                          `json:"recoveryTime,omitempty" yaml:"recoveryTime" bson:"recoveryTime" mapstructure:"RecoveryTime"`
	NfServicePersistence                    bool                                `json:"nfServicePersistence,omitempty" yaml:"nfServicePersistence" bson:"nfServicePersistence" mapstructure:"NfServicePersistence"`
	NfServices                              *[]NfService                        `json:"nfServices,omitempty" yaml:"nfServices" bson:"nfServices" mapstructure:"NfServices"`
	NfServiceList                           *map[string]NfService               `json:"nfServiceList,omitempty" yaml:"nfServiceList" bson:"nfServiceList" mapstructure:"NfServiceList"`
	NfProfileChangesSupportInd              bool                                `json:"nfProfileChangesSupportInd,omitempty" yaml:"nfProfileChangesSupportInd" bson:"nfProfileChangesSupportInd" mapstructure:"NfProfileChangesSupportInd"`
	NfProfilePartialUpdateChangesSupportInd *bool                               `json:"nfProfilePartialUpdateChangesSupportInd,omitempty" yaml:"nfProfilePartialUpdateChangesSupportInd" bson:"nfProfilePartialUpdateChangesSupportInd" mapstructure:"NfProfilePartialUpdateChangesSupportInd"`
	NfProfileChangesInd                     bool                                `json:"nfProfileChangesInd,omitempty" yaml:"nfProfileChangesInd" bson:"nfProfileChangesInd" mapstructure:"NfProfileChangesInd"`
	DefaultNotificationSubscriptions        []DefaultNotificationSubscription   `json:"defaultNotificationSubscriptions,omitempty" yaml:"defaultNotificationSubscriptions" bson:"defaultNotificationSubscriptions" mapstructure:"DefaultNotificationSubscriptions"`
	LmfInfo                                 *LmfInfo                            `json:"lmfInfo,omitempty" yaml:"lmfInfo" bson:"lmfInfo" mapstructure:"LmfInfo"`
	GmlcInfo                                *GmlcInfo                           `json:"gmlcInfo,omitempty" yaml:"gmlcInfo" bson:"gmlcInfo" mapstructure:"GmlcInfo"`
	NfSetIdList                             []string                            `json:"nfSetIdList,omitempty" yaml:"nfSetIdList" bson:"nfSetIdList" mapstructure:"NfSetIdList"`
	ServingScope                            []string                            `json:"servingScope,omitempty" yaml:"servingScope" bson:"servingScope" mapstructure:"ServingScope"`
	LcHSupportInd                           *bool                               `json:"lcHSupportInd,omitempty" yaml:"lcHSupportInd" bson:"lcHSupportInd" mapstructure:"LcHSupportInd"`
	OlcHSupportInd                          *bool                               `json:"olcHSupportInd,omitempty" yaml:"olcHSupportInd" bson:"olcHSupportInd" mapstructure:"OlcHSupportInd"`
	NfSetRecoveryTimeList                   *map[string]time.Time               `json:"nfSetRecoveryTimeList,omitempty" yaml:"nfSetRecoveryTimeList" bson:"nfSetRecoveryTimeList" mapstructure:"NfSetRecoveryTimeList"`
	ServiceSetRecoveryTimeList              *map[string]time.Time               `json:"serviceSetRecoveryTimeList,omitempty" yaml:"serviceSetRecoveryTimeList" bson:"serviceSetRecoveryTimeList" mapstructure:"ServiceSetRecoveryTimeList"`
	ScpDomains                              []string                            `json:"scpDomains,omitempty" yaml:"scpDomains" bson:"scpDomains" mapstructure:"ScpDomains"`
	ScpInfo                                 *ScpInfo                            `json:"scpInfo,omitempty" yaml:"scpInfo" bson:"scpInfo" mapstructure:"ScpInfo"`
	SeppInfo                                *SeppInfo                           `json:"seppInfo,omitempty" yaml:"seppInfo" bson:"seppInfo" mapstructure:"SeppInfo"`
	VendorId                                *string                             `json:"vendorId,omitempty" yaml:"vendorId" bson:"vendorId" mapstructure:"VendorId"`
	SupportedVendorSpecificFeatures         *map[string][]VendorSpecificFeature `json:"supportedVendorSpecificFeatures,omitempty" yaml:"supportedVendorSpecificFeatures" bson:"supportedVendorSpecificFeatures" mapstructure:"SupportedVendorSpecificFeatures"`
	AanfInfoList                            *map[string]AanfInfo                `json:"aanfInfoList,omitempty" yaml:"aanfInfoList" bson:"aanfInfoList" mapstructure:"AanfInfoList"`
	Var5gDdnmfInfo                          *Model5GDdnmfInfo                   `json:"5gDdnmfInfo,omitempty" yaml:"5gDdnmfInfo" bson:"5gDdnmfInfo" mapstructure:"Var5gDdnmfInfo"`
	MfafInfo                                *MfafInfo                           `json:"mfafInfo,omitempty" yaml:"mfafInfo" bson:"mfafInfo" mapstructure:"MfafInfo"`
	EasdfInfoList                           *map[string]EasdfInfo               `json:"easdfInfoList,omitempty" yaml:"easdfInfoList" bson:"easdfInfoList" mapstructure:"EasdfInfoList"`
	DccfInfo                                *DccfInfo                           `json:"dccfInfo,omitempty" yaml:"dccfInfo" bson:"dccfInfo" mapstructure:"DccfInfo"`
	NsacfInfoList                           *map[string]NsacfInfo               `json:"nsacfInfoList,omitempty" yaml:"nsacfInfoList" bson:"nsacfInfoList" mapstructure:"NsacfInfoList"`
	MbSmfInfoList                           *map[string]MbSmfInfo               `json:"mbSmfInfoList,omitempty" yaml:"mbSmfInfoList" bson:"mbSmfInfoList" mapstructure:"MbSmfInfoList"`
	TsctsfInfoList                          *map[string]TsctsfInfo              `json:"tsctsfInfoList,omitempty" yaml:"tsctsfInfoList" bson:"tsctsfInfoList" mapstructure:"TsctsfInfoList"`
	MbUpfInfoList                           *map[string]MbUpfInfo               `json:"mbUpfInfoList,omitempty" yaml:"mbUpfInfoList" bson:"mbUpfInfoList" mapstructure:"MbUpfInfoList"`
	TrustAfInfo                             *TrustAfInfo                        `json:"trustAfInfo,omitempty" yaml:"trustAfInfo" bson:"trustAfInfo" mapstructure:"TrustAfInfo"`
	NssaafInfo                              *NssaafInfo                         `json:"nssaafInfo,omitempty" yaml:"nssaafInfo" bson:"nssaafInfo" mapstructure:"NssaafInfo"`
	HniList                                 []string                            `json:"hniList,omitempty" yaml:"hniList" bson:"hniList" mapstructure:"HniList"`
	IwmscInfo                               *IwmscInfo                          `json:"iwmscInfo,omitempty" yaml:"iwmscInfo" bson:"iwmscInfo" mapstructure:"IwmscInfo"`
	MnpfInfo                                *MnpfInfo                           `json:"mnpfInfo,omitempty" yaml:"mnpfInfo" bson:"mnpfInfo" mapstructure:"MnpfInfo"`
	SmsfInfo                                *SmsfInfo                           `json:"smsfInfo,omitempty" yaml:"smsfInfo" bson:"smsfInfo" mapstructure:"SmsfInfo"`
	DcsfInfoList                            *map[string]DcsfInfo                `json:"dcsfInfoList,omitempty" yaml:"dcsfInfoList" bson:"dcsfInfoList" mapstructure:"DcsfInfoList"`
	MrfInfoList                             *map[string]MrfInfo                 `json:"mrfInfoList,omitempty" yaml:"mrfInfoList" bson:"mrfInfoList" mapstructure:"MrfInfoList"`
	MrfpInfoList                            *map[string]MrfpInfo                `json:"mrfpInfoList,omitempty" yaml:"mrfpInfoList" bson:"mrfpInfoList" mapstructure:"MrfpInfoList"`
	MfInfoList                              *map[string]MfInfo                  `json:"mfInfoList,omitempty" yaml:"mfInfoList" bson:"mfInfoList" mapstructure:"MfInfoList"`
	AdrfInfoList                            *map[string]AdrfInfo                `json:"adrfInfoList,omitempty" yaml:"adrfInfoList" bson:"adrfInfoList" mapstructure:"AdrfInfoList"`
	SelectionConditions                     *SelectionConditions                `json:"selectionConditions,omitempty" yaml:"selectionConditions" bson:"selectionConditions" mapstructure:"SelectionConditions"`
	CanaryRelease                           *bool                               `json:"canaryRelease,omitempty" yaml:"canaryRelease" bson:"canaryRelease" mapstructure:"CanaryRelease"`
	ExclusiveCanaryReleaseSelection         *bool                               `json:"exclusiveCanaryReleaseSelection,omitempty" yaml:"exclusiveCanaryReleaseSelection" bson:"exclusiveCanaryReleaseSelection" mapstructure:"ExclusiveCanaryReleaseSelection"`
	SharedProfileDataId                     *string                             `json:"sharedProfileDataId,omitempty" yaml:"sharedProfileDataId" bson:"sharedProfileDataId" mapstructure:"SharedProfileDataId"`
	ShutdownTime                            *time.Time                          `json:"shutdownTime,omitempty" yaml:"shutdownTime" bson:"shutdownTime" mapstructure:"ShutdownTime"`
	SupportedRcfs                           []string                            `json:"supportedRcfs,omitempty" yaml:"supportedRcfs" bson:"supportedRcfs" mapstructure:"SupportedRcfs"`
	CanaryPrecedenceOverPreferred           *bool                               `json:"canaryPrecedenceOverPreferred,omitempty" yaml:"canaryPrecedenceOverPreferred" bson:"canaryPrecedenceOverPreferred" mapstructure:"CanaryPrecedenceOverPreferred"`
	ImsasInfoList                           *map[string]ImsasInfo               `json:"imsasInfoList,omitempty" yaml:"imsasInfoList" bson:"imsasInfoList" mapstructure:"ImsasInfoList"`
}
