/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// CallbackUriPrefixItem callback URI prefix value to be used for specific notification types
type CallbackUriPrefixItem struct {
	CallbackUriPrefix string   `json:"callbackUriPrefix"`
	NotificationTypes []string `json:"notificationTypes"`
}

type _CallbackUriPrefixItem CallbackUriPrefixItem

// NewCallbackUriPrefixItem instantiates a new CallbackUriPrefixItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallbackUriPrefixItem(callbackUriPrefix string, notificationTypes []string) *CallbackUriPrefixItem {
	this := CallbackUriPrefixItem{}
	this.CallbackUriPrefix = callbackUriPrefix
	this.NotificationTypes = notificationTypes
	return &this
}

// NewCallbackUriPrefixItemWithDefaults instantiates a new CallbackUriPrefixItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallbackUriPrefixItemWithDefaults() *CallbackUriPrefixItem {
	this := CallbackUriPrefixItem{}
	return &this
}

// GetCallbackUriPrefix returns the CallbackUriPrefix field value
func (o *CallbackUriPrefixItem) GetCallbackUriPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallbackUriPrefix
}

// GetCallbackUriPrefixOk returns a tuple with the CallbackUriPrefix field value
// and a boolean to check if the value has been set.
func (o *CallbackUriPrefixItem) GetCallbackUriPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallbackUriPrefix, true
}

// SetCallbackUriPrefix sets field value
func (o *CallbackUriPrefixItem) SetCallbackUriPrefix(v string) {
	o.CallbackUriPrefix = v
}

// GetNotificationTypes returns the NotificationTypes field value
func (o *CallbackUriPrefixItem) GetNotificationTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.NotificationTypes
}

// GetNotificationTypesOk returns a tuple with the NotificationTypes field value
// and a boolean to check if the value has been set.
func (o *CallbackUriPrefixItem) GetNotificationTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NotificationTypes, true
}

// SetNotificationTypes sets field value
func (o *CallbackUriPrefixItem) SetNotificationTypes(v []string) {
	o.NotificationTypes = v
}

func (o CallbackUriPrefixItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallbackUriPrefixItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["callbackUriPrefix"] = o.CallbackUriPrefix
	toSerialize["notificationTypes"] = o.NotificationTypes
	return toSerialize, nil
}

func (o *CallbackUriPrefixItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"callbackUriPrefix",
		"notificationTypes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCallbackUriPrefixItem := _CallbackUriPrefixItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCallbackUriPrefixItem)

	if err != nil {
		return err
	}

	*o = CallbackUriPrefixItem(varCallbackUriPrefixItem)

	return err
}

type NullableCallbackUriPrefixItem struct {
	value *CallbackUriPrefixItem
	isSet bool
}

func (v NullableCallbackUriPrefixItem) Get() *CallbackUriPrefixItem {
	return v.value
}

func (v *NullableCallbackUriPrefixItem) Set(val *CallbackUriPrefixItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCallbackUriPrefixItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCallbackUriPrefixItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallbackUriPrefixItem(val *CallbackUriPrefixItem) *NullableCallbackUriPrefixItem {
	return &NullableCallbackUriPrefixItem{value: val, isSet: true}
}

func (v NullableCallbackUriPrefixItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallbackUriPrefixItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
