/*
NRF NFManagement Service

NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.4.0-alpha.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the MrfpInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MrfpInfo{}

// MrfpInfo Information of a Mrfp NF Instance
type MrfpInfo struct {
	MediaCapabilityList []string `json:"mediaCapabilityList,omitempty"`
}

// NewMrfpInfo instantiates a new MrfpInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMrfpInfo() *MrfpInfo {
	this := MrfpInfo{}
	return &this
}

// NewMrfpInfoWithDefaults instantiates a new MrfpInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMrfpInfoWithDefaults() *MrfpInfo {
	this := MrfpInfo{}
	return &this
}

// GetMediaCapabilityList returns the MediaCapabilityList field value if set, zero value otherwise.
func (o *MrfpInfo) GetMediaCapabilityList() []string {
	if o == nil || IsNil(o.MediaCapabilityList) {
		var ret []string
		return ret
	}
	return o.MediaCapabilityList
}

// GetMediaCapabilityListOk returns a tuple with the MediaCapabilityList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MrfpInfo) GetMediaCapabilityListOk() ([]string, bool) {
	if o == nil || IsNil(o.MediaCapabilityList) {
		return nil, false
	}
	return o.MediaCapabilityList, true
}

// HasMediaCapabilityList returns a boolean if a field has been set.
func (o *MrfpInfo) HasMediaCapabilityList() bool {
	if o != nil && !IsNil(o.MediaCapabilityList) {
		return true
	}

	return false
}

// SetMediaCapabilityList gets a reference to the given []string and assigns it to the MediaCapabilityList field.
func (o *MrfpInfo) SetMediaCapabilityList(v []string) {
	o.MediaCapabilityList = v
}

func (o MrfpInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MrfpInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MediaCapabilityList) {
		toSerialize["mediaCapabilityList"] = o.MediaCapabilityList
	}
	return toSerialize, nil
}

type NullableMrfpInfo struct {
	value *MrfpInfo
	isSet bool
}

func (v NullableMrfpInfo) Get() *MrfpInfo {
	return v.value
}

func (v *NullableMrfpInfo) Set(val *MrfpInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableMrfpInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableMrfpInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMrfpInfo(val *MrfpInfo) *NullableMrfpInfo {
	return &NullableMrfpInfo{value: val, isSet: true}
}

func (v NullableMrfpInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMrfpInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
