// Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the NfService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NfService{}

// NfService Information of a given NF Service Instance; it is part of the NFProfile of an NF Instance
type NfService struct {
	ServiceInstanceId string             `json:"serviceInstanceId"`
	ServiceName       ServiceName        `json:"serviceName"`
	Versions          []NfServiceVersion `json:"versions"`
	Scheme            UriScheme          `json:"scheme"`
	NfServiceStatus   NfServiceStatus    `json:"nfServiceStatus"`
	// Fully Qualified Domain Name
	Fqdn *string `json:"fqdn,omitempty"`
	// Fully Qualified Domain Name
	InterPlmnFqdn                    *string                           `json:"interPlmnFqdn,omitempty"`
	IpEndPoints                      []IpEndPoint                      `json:"ipEndPoints,omitempty"`
	ApiPrefix                        *string                           `json:"apiPrefix,omitempty"`
	CallbackUriPrefixList            []CallbackUriPrefixItem           `json:"callbackUriPrefixList,omitempty"`
	DefaultNotificationSubscriptions []DefaultNotificationSubscription `json:"defaultNotificationSubscriptions,omitempty"`
	AllowedPlmns                     []PlmnId                          `json:"allowedPlmns,omitempty"`
	AllowedSnpns                     []PlmnIdNid                       `json:"allowedSnpns,omitempty"`
	AllowedNfTypes                   []NfType                          `json:"allowedNfTypes,omitempty"`
	AllowedNfDomains                 []string                          `json:"allowedNfDomains,omitempty"`
	AllowedNssais                    []ExtSnssai                       `json:"allowedNssais,omitempty"`
	// A map (list of key-value pairs) where NF Type serves as key
	AllowedOperationsPerNfType *map[string][]string `json:"allowedOperationsPerNfType,omitempty"`
	// A map (list of key-value pairs) where NF Instance Id serves as key
	AllowedOperationsPerNfInstance          *map[string][]string `json:"allowedOperationsPerNfInstance,omitempty"`
	AllowedOperationsPerNfInstanceOverrides *bool                `json:"allowedOperationsPerNfInstanceOverrides,omitempty"`
	// A map (list of key-value pairs) where a valid JSON pointer Id serves as key
	AllowedScopesRuleSet *map[string]RuleSet `json:"allowedScopesRuleSet,omitempty"`
	Priority             *int32              `json:"priority,omitempty"`
	Capacity             *int32              `json:"capacity,omitempty"`
	Load                 *int32              `json:"load,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	LoadTimeStamp *time.Time `json:"loadTimeStamp,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	RecoveryTime *time.Time `json:"recoveryTime,omitempty"`
	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SupportedFeatures  *string      `json:"supportedFeatures,omitempty"`
	NfServiceSetIdList []string     `json:"nfServiceSetIdList,omitempty"`
	SNssais            []ExtSnssai  `json:"sNssais,omitempty"`
	PerPlmnSnssaiList  []PlmnSnssai `json:"perPlmnSnssaiList,omitempty"`
	// Vendor ID of the NF Service instance (Private Enterprise Number assigned by IANA)
	VendorId *string `json:"vendorId,omitempty"`
	// A map (list of key-value pairs) where IANA-assigned SMI Network Management Private Enterprise Codes serves as key
	SupportedVendorSpecificFeatures *map[string][]VendorSpecificFeature `json:"supportedVendorSpecificFeatures,omitempty"`
	Oauth2Required                  *bool                               `json:"oauth2Required,omitempty"`
	PerPlmnOauth2ReqList            *PlmnOauth2                         `json:"perPlmnOauth2ReqList,omitempty"`
	SelectionConditions             *SelectionConditions                `json:"selectionConditions,omitempty"`
	CanaryRelease                   *bool                               `json:"canaryRelease,omitempty"`
	ExclusiveCanaryReleaseSelection *bool                               `json:"exclusiveCanaryReleaseSelection,omitempty"`
	SharedServiceDataId             *string                             `json:"sharedServiceDataId,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	ShutdownTime                  *time.Time `json:"shutdownTime,omitempty"`
	CanaryPrecedenceOverPreferred *bool      `json:"canaryPrecedenceOverPreferred,omitempty"`
}

type _NfService NfService

// NewNfService instantiates a new NfService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNfService(serviceInstanceId string, serviceName ServiceName, versions []NfServiceVersion, scheme UriScheme, NfServiceStatus NfServiceStatus) *NfService {
	this := NfService{}
	this.ServiceInstanceId = serviceInstanceId
	this.ServiceName = serviceName
	this.Versions = versions
	this.Scheme = scheme
	this.NfServiceStatus = NfServiceStatus
	var allowedOperationsPerNfInstanceOverrides bool = false
	this.AllowedOperationsPerNfInstanceOverrides = &allowedOperationsPerNfInstanceOverrides
	var canaryRelease bool = false
	this.CanaryRelease = &canaryRelease
	var exclusiveCanaryReleaseSelection bool = false
	this.ExclusiveCanaryReleaseSelection = &exclusiveCanaryReleaseSelection
	var canaryPrecedenceOverPreferred bool = false
	this.CanaryPrecedenceOverPreferred = &canaryPrecedenceOverPreferred
	return &this
}

// NewNfServiceWithDefaults instantiates a new NfService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNfServiceWithDefaults() *NfService {
	this := NfService{}
	var allowedOperationsPerNfInstanceOverrides bool = false
	this.AllowedOperationsPerNfInstanceOverrides = &allowedOperationsPerNfInstanceOverrides
	var canaryRelease bool = false
	this.CanaryRelease = &canaryRelease
	var exclusiveCanaryReleaseSelection bool = false
	this.ExclusiveCanaryReleaseSelection = &exclusiveCanaryReleaseSelection
	var canaryPrecedenceOverPreferred bool = false
	this.CanaryPrecedenceOverPreferred = &canaryPrecedenceOverPreferred
	return &this
}

// GetServiceInstanceId returns the ServiceInstanceId field value
func (o *NfService) GetServiceInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceInstanceId
}

// GetServiceInstanceIdOk returns a tuple with the ServiceInstanceId field value
// and a boolean to check if the value has been set.
func (o *NfService) GetServiceInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceInstanceId, true
}

// SetServiceInstanceId sets field value
func (o *NfService) SetServiceInstanceId(v string) {
	o.ServiceInstanceId = v
}

// GetServiceName returns the ServiceName field value
func (o *NfService) GetServiceName() ServiceName {
	if o == nil {
		var ret ServiceName
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *NfService) GetServiceNameOk() (*ServiceName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *NfService) SetServiceName(v ServiceName) {
	o.ServiceName = v
}

// GetVersions returns the Versions field value
func (o *NfService) GetVersions() []NfServiceVersion {
	if o == nil {
		var ret []NfServiceVersion
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *NfService) GetVersionsOk() ([]NfServiceVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Versions, true
}

// SetVersions sets field value
func (o *NfService) SetVersions(v []NfServiceVersion) {
	o.Versions = v
}

// GetScheme returns the Scheme field value
func (o *NfService) GetScheme() UriScheme {
	if o == nil {
		var ret UriScheme
		return ret
	}

	return o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value
// and a boolean to check if the value has been set.
func (o *NfService) GetSchemeOk() (*UriScheme, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scheme, true
}

// SetScheme sets field value
func (o *NfService) SetScheme(v UriScheme) {
	o.Scheme = v
}

// GetNfServiceStatus returns the NfServiceStatus field value
func (o *NfService) GetNfServiceStatus() NfServiceStatus {
	if o == nil {
		var ret NfServiceStatus
		return ret
	}

	return o.NfServiceStatus
}

// GetNfServiceStatusOk returns a tuple with the NfServiceStatus field value
// and a boolean to check if the value has been set.
func (o *NfService) GetNfServiceStatusOk() (*NfServiceStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NfServiceStatus, true
}

// SetNfServiceStatus sets field value
func (o *NfService) SetNfServiceStatus(v NfServiceStatus) {
	o.NfServiceStatus = v
}

// GetFqdn returns the Fqdn field value if set, zero value otherwise.
func (o *NfService) GetFqdn() string {
	if o == nil || IsNil(o.Fqdn) {
		var ret string
		return ret
	}
	return *o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetFqdnOk() (*string, bool) {
	if o == nil || IsNil(o.Fqdn) {
		return nil, false
	}
	return o.Fqdn, true
}

// HasFqdn returns a boolean if a field has been set.
func (o *NfService) HasFqdn() bool {
	if o != nil && !IsNil(o.Fqdn) {
		return true
	}

	return false
}

// SetFqdn gets a reference to the given string and assigns it to the Fqdn field.
func (o *NfService) SetFqdn(v string) {
	o.Fqdn = &v
}

// GetInterPlmnFqdn returns the InterPlmnFqdn field value if set, zero value otherwise.
func (o *NfService) GetInterPlmnFqdn() string {
	if o == nil || IsNil(o.InterPlmnFqdn) {
		var ret string
		return ret
	}
	return *o.InterPlmnFqdn
}

// GetInterPlmnFqdnOk returns a tuple with the InterPlmnFqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetInterPlmnFqdnOk() (*string, bool) {
	if o == nil || IsNil(o.InterPlmnFqdn) {
		return nil, false
	}
	return o.InterPlmnFqdn, true
}

// HasInterPlmnFqdn returns a boolean if a field has been set.
func (o *NfService) HasInterPlmnFqdn() bool {
	if o != nil && !IsNil(o.InterPlmnFqdn) {
		return true
	}

	return false
}

// SetInterPlmnFqdn gets a reference to the given string and assigns it to the InterPlmnFqdn field.
func (o *NfService) SetInterPlmnFqdn(v string) {
	o.InterPlmnFqdn = &v
}

// GetIpEndPoints returns the IpEndPoints field value if set, zero value otherwise.
func (o *NfService) GetIpEndPoints() []IpEndPoint {
	if o == nil || IsNil(o.IpEndPoints) {
		var ret []IpEndPoint
		return ret
	}
	return o.IpEndPoints
}

// GetIpEndPointsOk returns a tuple with the IpEndPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetIpEndPointsOk() ([]IpEndPoint, bool) {
	if o == nil || IsNil(o.IpEndPoints) {
		return nil, false
	}
	return o.IpEndPoints, true
}

// HasIpEndPoints returns a boolean if a field has been set.
func (o *NfService) HasIpEndPoints() bool {
	if o != nil && !IsNil(o.IpEndPoints) {
		return true
	}

	return false
}

// SetIpEndPoints gets a reference to the given []IpEndPoint and assigns it to the IpEndPoints field.
func (o *NfService) SetIpEndPoints(v []IpEndPoint) {
	o.IpEndPoints = v
}

// GetApiPrefix returns the ApiPrefix field value if set, zero value otherwise.
func (o *NfService) GetApiPrefix() string {
	if o == nil || IsNil(o.ApiPrefix) {
		var ret string
		return ret
	}
	return *o.ApiPrefix
}

// GetApiPrefixOk returns a tuple with the ApiPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetApiPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.ApiPrefix) {
		return nil, false
	}
	return o.ApiPrefix, true
}

// HasApiPrefix returns a boolean if a field has been set.
func (o *NfService) HasApiPrefix() bool {
	if o != nil && !IsNil(o.ApiPrefix) {
		return true
	}

	return false
}

// SetApiPrefix gets a reference to the given string and assigns it to the ApiPrefix field.
func (o *NfService) SetApiPrefix(v string) {
	o.ApiPrefix = &v
}

// GetCallbackUriPrefixList returns the CallbackUriPrefixList field value if set, zero value otherwise.
func (o *NfService) GetCallbackUriPrefixList() []CallbackUriPrefixItem {
	if o == nil || IsNil(o.CallbackUriPrefixList) {
		var ret []CallbackUriPrefixItem
		return ret
	}
	return o.CallbackUriPrefixList
}

// GetCallbackUriPrefixListOk returns a tuple with the CallbackUriPrefixList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetCallbackUriPrefixListOk() ([]CallbackUriPrefixItem, bool) {
	if o == nil || IsNil(o.CallbackUriPrefixList) {
		return nil, false
	}
	return o.CallbackUriPrefixList, true
}

// HasCallbackUriPrefixList returns a boolean if a field has been set.
func (o *NfService) HasCallbackUriPrefixList() bool {
	if o != nil && !IsNil(o.CallbackUriPrefixList) {
		return true
	}

	return false
}

// SetCallbackUriPrefixList gets a reference to the given []CallbackUriPrefixItem and assigns it to the CallbackUriPrefixList field.
func (o *NfService) SetCallbackUriPrefixList(v []CallbackUriPrefixItem) {
	o.CallbackUriPrefixList = v
}

// GetDefaultNotificationSubscriptions returns the DefaultNotificationSubscriptions field value if set, zero value otherwise.
func (o *NfService) GetDefaultNotificationSubscriptions() []DefaultNotificationSubscription {
	if o == nil || IsNil(o.DefaultNotificationSubscriptions) {
		var ret []DefaultNotificationSubscription
		return ret
	}
	return o.DefaultNotificationSubscriptions
}

// GetDefaultNotificationSubscriptionsOk returns a tuple with the DefaultNotificationSubscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetDefaultNotificationSubscriptionsOk() ([]DefaultNotificationSubscription, bool) {
	if o == nil || IsNil(o.DefaultNotificationSubscriptions) {
		return nil, false
	}
	return o.DefaultNotificationSubscriptions, true
}

// HasDefaultNotificationSubscriptions returns a boolean if a field has been set.
func (o *NfService) HasDefaultNotificationSubscriptions() bool {
	if o != nil && !IsNil(o.DefaultNotificationSubscriptions) {
		return true
	}

	return false
}

// SetDefaultNotificationSubscriptions gets a reference to the given []DefaultNotificationSubscription and assigns it to the DefaultNotificationSubscriptions field.
func (o *NfService) SetDefaultNotificationSubscriptions(v []DefaultNotificationSubscription) {
	o.DefaultNotificationSubscriptions = v
}

// GetAllowedPlmns returns the AllowedPlmns field value if set, zero value otherwise.
func (o *NfService) GetAllowedPlmns() []PlmnId {
	if o == nil || IsNil(o.AllowedPlmns) {
		var ret []PlmnId
		return ret
	}
	return o.AllowedPlmns
}

// GetAllowedPlmnsOk returns a tuple with the AllowedPlmns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedPlmnsOk() ([]PlmnId, bool) {
	if o == nil || IsNil(o.AllowedPlmns) {
		return nil, false
	}
	return o.AllowedPlmns, true
}

// HasAllowedPlmns returns a boolean if a field has been set.
func (o *NfService) HasAllowedPlmns() bool {
	if o != nil && !IsNil(o.AllowedPlmns) {
		return true
	}

	return false
}

// SetAllowedPlmns gets a reference to the given []PlmnId and assigns it to the AllowedPlmns field.
func (o *NfService) SetAllowedPlmns(v []PlmnId) {
	o.AllowedPlmns = v
}

// GetAllowedSnpns returns the AllowedSnpns field value if set, zero value otherwise.
func (o *NfService) GetAllowedSnpns() []PlmnIdNid {
	if o == nil || IsNil(o.AllowedSnpns) {
		var ret []PlmnIdNid
		return ret
	}
	return o.AllowedSnpns
}

// GetAllowedSnpnsOk returns a tuple with the AllowedSnpns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedSnpnsOk() ([]PlmnIdNid, bool) {
	if o == nil || IsNil(o.AllowedSnpns) {
		return nil, false
	}
	return o.AllowedSnpns, true
}

// HasAllowedSnpns returns a boolean if a field has been set.
func (o *NfService) HasAllowedSnpns() bool {
	if o != nil && !IsNil(o.AllowedSnpns) {
		return true
	}

	return false
}

// SetAllowedSnpns gets a reference to the given []PlmnIdNid and assigns it to the AllowedSnpns field.
func (o *NfService) SetAllowedSnpns(v []PlmnIdNid) {
	o.AllowedSnpns = v
}

// GetAllowedNfTypes returns the AllowedNfTypes field value if set, zero value otherwise.
func (o *NfService) GetAllowedNfTypes() []NfType {
	if o == nil || IsNil(o.AllowedNfTypes) {
		var ret []NfType
		return ret
	}
	return o.AllowedNfTypes
}

// GetAllowedNfTypesOk returns a tuple with the AllowedNfTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedNfTypesOk() ([]NfType, bool) {
	if o == nil || IsNil(o.AllowedNfTypes) {
		return nil, false
	}
	return o.AllowedNfTypes, true
}

// HasAllowedNfTypes returns a boolean if a field has been set.
func (o *NfService) HasAllowedNfTypes() bool {
	if o != nil && !IsNil(o.AllowedNfTypes) {
		return true
	}

	return false
}

// SetAllowedNfTypes gets a reference to the given []NFType and assigns it to the AllowedNfTypes field.
func (o *NfService) SetAllowedNfTypes(v []NfType) {
	o.AllowedNfTypes = v
}

// GetAllowedNfDomains returns the AllowedNfDomains field value if set, zero value otherwise.
func (o *NfService) GetAllowedNfDomains() []string {
	if o == nil || IsNil(o.AllowedNfDomains) {
		var ret []string
		return ret
	}
	return o.AllowedNfDomains
}

// GetAllowedNfDomainsOk returns a tuple with the AllowedNfDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedNfDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedNfDomains) {
		return nil, false
	}
	return o.AllowedNfDomains, true
}

// HasAllowedNfDomains returns a boolean if a field has been set.
func (o *NfService) HasAllowedNfDomains() bool {
	if o != nil && !IsNil(o.AllowedNfDomains) {
		return true
	}

	return false
}

// SetAllowedNfDomains gets a reference to the given []string and assigns it to the AllowedNfDomains field.
func (o *NfService) SetAllowedNfDomains(v []string) {
	o.AllowedNfDomains = v
}

// GetAllowedNssais returns the AllowedNssais field value if set, zero value otherwise.
func (o *NfService) GetAllowedNssais() []ExtSnssai {
	if o == nil || IsNil(o.AllowedNssais) {
		var ret []ExtSnssai
		return ret
	}
	return o.AllowedNssais
}

// GetAllowedNssaisOk returns a tuple with the AllowedNssais field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedNssaisOk() ([]ExtSnssai, bool) {
	if o == nil || IsNil(o.AllowedNssais) {
		return nil, false
	}
	return o.AllowedNssais, true
}

// HasAllowedNssais returns a boolean if a field has been set.
func (o *NfService) HasAllowedNssais() bool {
	if o != nil && !IsNil(o.AllowedNssais) {
		return true
	}

	return false
}

// SetAllowedNssais gets a reference to the given []ExtSnssai and assigns it to the AllowedNssais field.
func (o *NfService) SetAllowedNssais(v []ExtSnssai) {
	o.AllowedNssais = v
}

// GetAllowedOperationsPerNfType returns the AllowedOperationsPerNfType field value if set, zero value otherwise.
func (o *NfService) GetAllowedOperationsPerNfType() map[string][]string {
	if o == nil || IsNil(o.AllowedOperationsPerNfType) {
		var ret map[string][]string
		return ret
	}
	return *o.AllowedOperationsPerNfType
}

// GetAllowedOperationsPerNfTypeOk returns a tuple with the AllowedOperationsPerNfType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedOperationsPerNfTypeOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.AllowedOperationsPerNfType) {
		return nil, false
	}
	return o.AllowedOperationsPerNfType, true
}

// HasAllowedOperationsPerNfType returns a boolean if a field has been set.
func (o *NfService) HasAllowedOperationsPerNfType() bool {
	if o != nil && !IsNil(o.AllowedOperationsPerNfType) {
		return true
	}

	return false
}

// SetAllowedOperationsPerNfType gets a reference to the given map[string][]string and assigns it to the AllowedOperationsPerNfType field.
func (o *NfService) SetAllowedOperationsPerNfType(v map[string][]string) {
	o.AllowedOperationsPerNfType = &v
}

// GetAllowedOperationsPerNfInstance returns the AllowedOperationsPerNfInstance field value if set, zero value otherwise.
func (o *NfService) GetAllowedOperationsPerNfInstance() map[string][]string {
	if o == nil || IsNil(o.AllowedOperationsPerNfInstance) {
		var ret map[string][]string
		return ret
	}
	return *o.AllowedOperationsPerNfInstance
}

// GetAllowedOperationsPerNfInstanceOk returns a tuple with the AllowedOperationsPerNfInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedOperationsPerNfInstanceOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.AllowedOperationsPerNfInstance) {
		return nil, false
	}
	return o.AllowedOperationsPerNfInstance, true
}

// HasAllowedOperationsPerNfInstance returns a boolean if a field has been set.
func (o *NfService) HasAllowedOperationsPerNfInstance() bool {
	if o != nil && !IsNil(o.AllowedOperationsPerNfInstance) {
		return true
	}

	return false
}

// SetAllowedOperationsPerNfInstance gets a reference to the given map[string][]string and assigns it to the AllowedOperationsPerNfInstance field.
func (o *NfService) SetAllowedOperationsPerNfInstance(v map[string][]string) {
	o.AllowedOperationsPerNfInstance = &v
}

// GetAllowedOperationsPerNfInstanceOverrides returns the AllowedOperationsPerNfInstanceOverrides field value if set, zero value otherwise.
func (o *NfService) GetAllowedOperationsPerNfInstanceOverrides() bool {
	if o == nil || IsNil(o.AllowedOperationsPerNfInstanceOverrides) {
		var ret bool
		return ret
	}
	return *o.AllowedOperationsPerNfInstanceOverrides
}

// GetAllowedOperationsPerNfInstanceOverridesOk returns a tuple with the AllowedOperationsPerNfInstanceOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedOperationsPerNfInstanceOverridesOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowedOperationsPerNfInstanceOverrides) {
		return nil, false
	}
	return o.AllowedOperationsPerNfInstanceOverrides, true
}

// HasAllowedOperationsPerNfInstanceOverrides returns a boolean if a field has been set.
func (o *NfService) HasAllowedOperationsPerNfInstanceOverrides() bool {
	if o != nil && !IsNil(o.AllowedOperationsPerNfInstanceOverrides) {
		return true
	}

	return false
}

// SetAllowedOperationsPerNfInstanceOverrides gets a reference to the given bool and assigns it to the AllowedOperationsPerNfInstanceOverrides field.
func (o *NfService) SetAllowedOperationsPerNfInstanceOverrides(v bool) {
	o.AllowedOperationsPerNfInstanceOverrides = &v
}

// GetAllowedScopesRuleSet returns the AllowedScopesRuleSet field value if set, zero value otherwise.
func (o *NfService) GetAllowedScopesRuleSet() map[string]RuleSet {
	if o == nil || IsNil(o.AllowedScopesRuleSet) {
		var ret map[string]RuleSet
		return ret
	}
	return *o.AllowedScopesRuleSet
}

// GetAllowedScopesRuleSetOk returns a tuple with the AllowedScopesRuleSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetAllowedScopesRuleSetOk() (*map[string]RuleSet, bool) {
	if o == nil || IsNil(o.AllowedScopesRuleSet) {
		return nil, false
	}
	return o.AllowedScopesRuleSet, true
}

// HasAllowedScopesRuleSet returns a boolean if a field has been set.
func (o *NfService) HasAllowedScopesRuleSet() bool {
	if o != nil && !IsNil(o.AllowedScopesRuleSet) {
		return true
	}

	return false
}

// SetAllowedScopesRuleSet gets a reference to the given map[string]RuleSet and assigns it to the AllowedScopesRuleSet field.
func (o *NfService) SetAllowedScopesRuleSet(v map[string]RuleSet) {
	o.AllowedScopesRuleSet = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *NfService) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *NfService) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *NfService) SetPriority(v int32) {
	o.Priority = &v
}

// GetCapacity returns the Capacity field value if set, zero value otherwise.
func (o *NfService) GetCapacity() int32 {
	if o == nil || IsNil(o.Capacity) {
		var ret int32
		return ret
	}
	return *o.Capacity
}

// GetCapacityOk returns a tuple with the Capacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetCapacityOk() (*int32, bool) {
	if o == nil || IsNil(o.Capacity) {
		return nil, false
	}
	return o.Capacity, true
}

// HasCapacity returns a boolean if a field has been set.
func (o *NfService) HasCapacity() bool {
	if o != nil && !IsNil(o.Capacity) {
		return true
	}

	return false
}

// SetCapacity gets a reference to the given int32 and assigns it to the Capacity field.
func (o *NfService) SetCapacity(v int32) {
	o.Capacity = &v
}

// GetLoad returns the Load field value if set, zero value otherwise.
func (o *NfService) GetLoad() int32 {
	if o == nil || IsNil(o.Load) {
		var ret int32
		return ret
	}
	return *o.Load
}

// GetLoadOk returns a tuple with the Load field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetLoadOk() (*int32, bool) {
	if o == nil || IsNil(o.Load) {
		return nil, false
	}
	return o.Load, true
}

// HasLoad returns a boolean if a field has been set.
func (o *NfService) HasLoad() bool {
	if o != nil && !IsNil(o.Load) {
		return true
	}

	return false
}

// SetLoad gets a reference to the given int32 and assigns it to the Load field.
func (o *NfService) SetLoad(v int32) {
	o.Load = &v
}

// GetLoadTimeStamp returns the LoadTimeStamp field value if set, zero value otherwise.
func (o *NfService) GetLoadTimeStamp() time.Time {
	if o == nil || IsNil(o.LoadTimeStamp) {
		var ret time.Time
		return ret
	}
	return *o.LoadTimeStamp
}

// GetLoadTimeStampOk returns a tuple with the LoadTimeStamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetLoadTimeStampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LoadTimeStamp) {
		return nil, false
	}
	return o.LoadTimeStamp, true
}

// HasLoadTimeStamp returns a boolean if a field has been set.
func (o *NfService) HasLoadTimeStamp() bool {
	if o != nil && !IsNil(o.LoadTimeStamp) {
		return true
	}

	return false
}

// SetLoadTimeStamp gets a reference to the given time.Time and assigns it to the LoadTimeStamp field.
func (o *NfService) SetLoadTimeStamp(v time.Time) {
	o.LoadTimeStamp = &v
}

// GetRecoveryTime returns the RecoveryTime field value if set, zero value otherwise.
func (o *NfService) GetRecoveryTime() time.Time {
	if o == nil || IsNil(o.RecoveryTime) {
		var ret time.Time
		return ret
	}
	return *o.RecoveryTime
}

// GetRecoveryTimeOk returns a tuple with the RecoveryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetRecoveryTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RecoveryTime) {
		return nil, false
	}
	return o.RecoveryTime, true
}

// HasRecoveryTime returns a boolean if a field has been set.
func (o *NfService) HasRecoveryTime() bool {
	if o != nil && !IsNil(o.RecoveryTime) {
		return true
	}

	return false
}

// SetRecoveryTime gets a reference to the given time.Time and assigns it to the RecoveryTime field.
func (o *NfService) SetRecoveryTime(v time.Time) {
	o.RecoveryTime = &v
}

// GetSupportedFeatures returns the SupportedFeatures field value if set, zero value otherwise.
func (o *NfService) GetSupportedFeatures() string {
	if o == nil || IsNil(o.SupportedFeatures) {
		var ret string
		return ret
	}
	return *o.SupportedFeatures
}

// GetSupportedFeaturesOk returns a tuple with the SupportedFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetSupportedFeaturesOk() (*string, bool) {
	if o == nil || IsNil(o.SupportedFeatures) {
		return nil, false
	}
	return o.SupportedFeatures, true
}

// HasSupportedFeatures returns a boolean if a field has been set.
func (o *NfService) HasSupportedFeatures() bool {
	if o != nil && !IsNil(o.SupportedFeatures) {
		return true
	}

	return false
}

// SetSupportedFeatures gets a reference to the given string and assigns it to the SupportedFeatures field.
func (o *NfService) SetSupportedFeatures(v string) {
	o.SupportedFeatures = &v
}

// GetNfServiceSetIdList returns the NfServiceSetIdList field value if set, zero value otherwise.
func (o *NfService) GetNfServiceSetIdList() []string {
	if o == nil || IsNil(o.NfServiceSetIdList) {
		var ret []string
		return ret
	}
	return o.NfServiceSetIdList
}

// GetNfServiceSetIdListOk returns a tuple with the NfServiceSetIdList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetNfServiceSetIdListOk() ([]string, bool) {
	if o == nil || IsNil(o.NfServiceSetIdList) {
		return nil, false
	}
	return o.NfServiceSetIdList, true
}

// HasNfServiceSetIdList returns a boolean if a field has been set.
func (o *NfService) HasNfServiceSetIdList() bool {
	if o != nil && !IsNil(o.NfServiceSetIdList) {
		return true
	}

	return false
}

// SetNfServiceSetIdList gets a reference to the given []string and assigns it to the NfServiceSetIdList field.
func (o *NfService) SetNfServiceSetIdList(v []string) {
	o.NfServiceSetIdList = v
}

// GetSNssais returns the SNssais field value if set, zero value otherwise.
func (o *NfService) GetSNssais() []ExtSnssai {
	if o == nil || IsNil(o.SNssais) {
		var ret []ExtSnssai
		return ret
	}
	return o.SNssais
}

// GetSNssaisOk returns a tuple with the SNssais field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetSNssaisOk() ([]ExtSnssai, bool) {
	if o == nil || IsNil(o.SNssais) {
		return nil, false
	}
	return o.SNssais, true
}

// HasSNssais returns a boolean if a field has been set.
func (o *NfService) HasSNssais() bool {
	if o != nil && !IsNil(o.SNssais) {
		return true
	}

	return false
}

// SetSNssais gets a reference to the given []ExtSnssai and assigns it to the SNssais field.
func (o *NfService) SetSNssais(v []ExtSnssai) {
	o.SNssais = v
}

// GetPerPlmnSnssaiList returns the PerPlmnSnssaiList field value if set, zero value otherwise.
func (o *NfService) GetPerPlmnSnssaiList() []PlmnSnssai {
	if o == nil || IsNil(o.PerPlmnSnssaiList) {
		var ret []PlmnSnssai
		return ret
	}
	return o.PerPlmnSnssaiList
}

// GetPerPlmnSnssaiListOk returns a tuple with the PerPlmnSnssaiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetPerPlmnSnssaiListOk() ([]PlmnSnssai, bool) {
	if o == nil || IsNil(o.PerPlmnSnssaiList) {
		return nil, false
	}
	return o.PerPlmnSnssaiList, true
}

// HasPerPlmnSnssaiList returns a boolean if a field has been set.
func (o *NfService) HasPerPlmnSnssaiList() bool {
	if o != nil && !IsNil(o.PerPlmnSnssaiList) {
		return true
	}

	return false
}

// SetPerPlmnSnssaiList gets a reference to the given []PlmnSnssai and assigns it to the PerPlmnSnssaiList field.
func (o *NfService) SetPerPlmnSnssaiList(v []PlmnSnssai) {
	o.PerPlmnSnssaiList = v
}

// GetVendorId returns the VendorId field value if set, zero value otherwise.
func (o *NfService) GetVendorId() string {
	if o == nil || IsNil(o.VendorId) {
		var ret string
		return ret
	}
	return *o.VendorId
}

// GetVendorIdOk returns a tuple with the VendorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetVendorIdOk() (*string, bool) {
	if o == nil || IsNil(o.VendorId) {
		return nil, false
	}
	return o.VendorId, true
}

// HasVendorId returns a boolean if a field has been set.
func (o *NfService) HasVendorId() bool {
	if o != nil && !IsNil(o.VendorId) {
		return true
	}

	return false
}

// SetVendorId gets a reference to the given string and assigns it to the VendorId field.
func (o *NfService) SetVendorId(v string) {
	o.VendorId = &v
}

// GetSupportedVendorSpecificFeatures returns the SupportedVendorSpecificFeatures field value if set, zero value otherwise.
func (o *NfService) GetSupportedVendorSpecificFeatures() map[string][]VendorSpecificFeature {
	if o == nil || IsNil(o.SupportedVendorSpecificFeatures) {
		var ret map[string][]VendorSpecificFeature
		return ret
	}
	return *o.SupportedVendorSpecificFeatures
}

// GetSupportedVendorSpecificFeaturesOk returns a tuple with the SupportedVendorSpecificFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetSupportedVendorSpecificFeaturesOk() (*map[string][]VendorSpecificFeature, bool) {
	if o == nil || IsNil(o.SupportedVendorSpecificFeatures) {
		return nil, false
	}
	return o.SupportedVendorSpecificFeatures, true
}

// HasSupportedVendorSpecificFeatures returns a boolean if a field has been set.
func (o *NfService) HasSupportedVendorSpecificFeatures() bool {
	if o != nil && !IsNil(o.SupportedVendorSpecificFeatures) {
		return true
	}

	return false
}

// SetSupportedVendorSpecificFeatures gets a reference to the given map[string][]VendorSpecificFeature and assigns it to the SupportedVendorSpecificFeatures field.
func (o *NfService) SetSupportedVendorSpecificFeatures(v map[string][]VendorSpecificFeature) {
	o.SupportedVendorSpecificFeatures = &v
}

// GetOauth2Required returns the Oauth2Required field value if set, zero value otherwise.
func (o *NfService) GetOauth2Required() bool {
	if o == nil || IsNil(o.Oauth2Required) {
		var ret bool
		return ret
	}
	return *o.Oauth2Required
}

// GetOauth2RequiredOk returns a tuple with the Oauth2Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetOauth2RequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Oauth2Required) {
		return nil, false
	}
	return o.Oauth2Required, true
}

// HasOauth2Required returns a boolean if a field has been set.
func (o *NfService) HasOauth2Required() bool {
	if o != nil && !IsNil(o.Oauth2Required) {
		return true
	}

	return false
}

// SetOauth2Required gets a reference to the given bool and assigns it to the Oauth2Required field.
func (o *NfService) SetOauth2Required(v bool) {
	o.Oauth2Required = &v
}

// GetPerPlmnOauth2ReqList returns the PerPlmnOauth2ReqList field value if set, zero value otherwise.
func (o *NfService) GetPerPlmnOauth2ReqList() PlmnOauth2 {
	if o == nil || IsNil(o.PerPlmnOauth2ReqList) {
		var ret PlmnOauth2
		return ret
	}
	return *o.PerPlmnOauth2ReqList
}

// GetPerPlmnOauth2ReqListOk returns a tuple with the PerPlmnOauth2ReqList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetPerPlmnOauth2ReqListOk() (*PlmnOauth2, bool) {
	if o == nil || IsNil(o.PerPlmnOauth2ReqList) {
		return nil, false
	}
	return o.PerPlmnOauth2ReqList, true
}

// HasPerPlmnOauth2ReqList returns a boolean if a field has been set.
func (o *NfService) HasPerPlmnOauth2ReqList() bool {
	if o != nil && !IsNil(o.PerPlmnOauth2ReqList) {
		return true
	}

	return false
}

// SetPerPlmnOauth2ReqList gets a reference to the given PlmnOauth2 and assigns it to the PerPlmnOauth2ReqList field.
func (o *NfService) SetPerPlmnOauth2ReqList(v PlmnOauth2) {
	o.PerPlmnOauth2ReqList = &v
}

// GetSelectionConditions returns the SelectionConditions field value if set, zero value otherwise.
func (o *NfService) GetSelectionConditions() SelectionConditions {
	if o == nil || IsNil(o.SelectionConditions) {
		var ret SelectionConditions
		return ret
	}
	return *o.SelectionConditions
}

// GetSelectionConditionsOk returns a tuple with the SelectionConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetSelectionConditionsOk() (*SelectionConditions, bool) {
	if o == nil || IsNil(o.SelectionConditions) {
		return nil, false
	}
	return o.SelectionConditions, true
}

// HasSelectionConditions returns a boolean if a field has been set.
func (o *NfService) HasSelectionConditions() bool {
	if o != nil && !IsNil(o.SelectionConditions) {
		return true
	}

	return false
}

// SetSelectionConditions gets a reference to the given SelectionConditions and assigns it to the SelectionConditions field.
func (o *NfService) SetSelectionConditions(v SelectionConditions) {
	o.SelectionConditions = &v
}

// GetCanaryRelease returns the CanaryRelease field value if set, zero value otherwise.
func (o *NfService) GetCanaryRelease() bool {
	if o == nil || IsNil(o.CanaryRelease) {
		var ret bool
		return ret
	}
	return *o.CanaryRelease
}

// GetCanaryReleaseOk returns a tuple with the CanaryRelease field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetCanaryReleaseOk() (*bool, bool) {
	if o == nil || IsNil(o.CanaryRelease) {
		return nil, false
	}
	return o.CanaryRelease, true
}

// HasCanaryRelease returns a boolean if a field has been set.
func (o *NfService) HasCanaryRelease() bool {
	if o != nil && !IsNil(o.CanaryRelease) {
		return true
	}

	return false
}

// SetCanaryRelease gets a reference to the given bool and assigns it to the CanaryRelease field.
func (o *NfService) SetCanaryRelease(v bool) {
	o.CanaryRelease = &v
}

// GetExclusiveCanaryReleaseSelection returns the ExclusiveCanaryReleaseSelection field value if set, zero value otherwise.
func (o *NfService) GetExclusiveCanaryReleaseSelection() bool {
	if o == nil || IsNil(o.ExclusiveCanaryReleaseSelection) {
		var ret bool
		return ret
	}
	return *o.ExclusiveCanaryReleaseSelection
}

// GetExclusiveCanaryReleaseSelectionOk returns a tuple with the ExclusiveCanaryReleaseSelection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetExclusiveCanaryReleaseSelectionOk() (*bool, bool) {
	if o == nil || IsNil(o.ExclusiveCanaryReleaseSelection) {
		return nil, false
	}
	return o.ExclusiveCanaryReleaseSelection, true
}

// HasExclusiveCanaryReleaseSelection returns a boolean if a field has been set.
func (o *NfService) HasExclusiveCanaryReleaseSelection() bool {
	if o != nil && !IsNil(o.ExclusiveCanaryReleaseSelection) {
		return true
	}

	return false
}

// SetExclusiveCanaryReleaseSelection gets a reference to the given bool and assigns it to the ExclusiveCanaryReleaseSelection field.
func (o *NfService) SetExclusiveCanaryReleaseSelection(v bool) {
	o.ExclusiveCanaryReleaseSelection = &v
}

// GetSharedServiceDataId returns the SharedServiceDataId field value if set, zero value otherwise.
func (o *NfService) GetSharedServiceDataId() string {
	if o == nil || IsNil(o.SharedServiceDataId) {
		var ret string
		return ret
	}
	return *o.SharedServiceDataId
}

// GetSharedServiceDataIdOk returns a tuple with the SharedServiceDataId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetSharedServiceDataIdOk() (*string, bool) {
	if o == nil || IsNil(o.SharedServiceDataId) {
		return nil, false
	}
	return o.SharedServiceDataId, true
}

// HasSharedServiceDataId returns a boolean if a field has been set.
func (o *NfService) HasSharedServiceDataId() bool {
	if o != nil && !IsNil(o.SharedServiceDataId) {
		return true
	}

	return false
}

// SetSharedServiceDataId gets a reference to the given string and assigns it to the SharedServiceDataId field.
func (o *NfService) SetSharedServiceDataId(v string) {
	o.SharedServiceDataId = &v
}

// GetShutdownTime returns the ShutdownTime field value if set, zero value otherwise.
func (o *NfService) GetShutdownTime() time.Time {
	if o == nil || IsNil(o.ShutdownTime) {
		var ret time.Time
		return ret
	}
	return *o.ShutdownTime
}

// GetShutdownTimeOk returns a tuple with the ShutdownTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetShutdownTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ShutdownTime) {
		return nil, false
	}
	return o.ShutdownTime, true
}

// HasShutdownTime returns a boolean if a field has been set.
func (o *NfService) HasShutdownTime() bool {
	if o != nil && !IsNil(o.ShutdownTime) {
		return true
	}

	return false
}

// SetShutdownTime gets a reference to the given time.Time and assigns it to the ShutdownTime field.
func (o *NfService) SetShutdownTime(v time.Time) {
	o.ShutdownTime = &v
}

// GetCanaryPrecedenceOverPreferred returns the CanaryPrecedenceOverPreferred field value if set, zero value otherwise.
func (o *NfService) GetCanaryPrecedenceOverPreferred() bool {
	if o == nil || IsNil(o.CanaryPrecedenceOverPreferred) {
		var ret bool
		return ret
	}
	return *o.CanaryPrecedenceOverPreferred
}

// GetCanaryPrecedenceOverPreferredOk returns a tuple with the CanaryPrecedenceOverPreferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfService) GetCanaryPrecedenceOverPreferredOk() (*bool, bool) {
	if o == nil || IsNil(o.CanaryPrecedenceOverPreferred) {
		return nil, false
	}
	return o.CanaryPrecedenceOverPreferred, true
}

// HasCanaryPrecedenceOverPreferred returns a boolean if a field has been set.
func (o *NfService) HasCanaryPrecedenceOverPreferred() bool {
	if o != nil && !IsNil(o.CanaryPrecedenceOverPreferred) {
		return true
	}

	return false
}

// SetCanaryPrecedenceOverPreferred gets a reference to the given bool and assigns it to the CanaryPrecedenceOverPreferred field.
func (o *NfService) SetCanaryPrecedenceOverPreferred(v bool) {
	o.CanaryPrecedenceOverPreferred = &v
}

func (o NfService) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NfService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serviceInstanceId"] = o.ServiceInstanceId
	toSerialize["serviceName"] = o.ServiceName
	toSerialize["versions"] = o.Versions
	toSerialize["scheme"] = o.Scheme
	toSerialize["NfServiceStatus"] = o.NfServiceStatus
	if !IsNil(o.Fqdn) {
		toSerialize["fqdn"] = o.Fqdn
	}
	if !IsNil(o.InterPlmnFqdn) {
		toSerialize["interPlmnFqdn"] = o.InterPlmnFqdn
	}
	if !IsNil(o.IpEndPoints) {
		toSerialize["ipEndPoints"] = o.IpEndPoints
	}
	if !IsNil(o.ApiPrefix) {
		toSerialize["apiPrefix"] = o.ApiPrefix
	}
	if !IsNil(o.CallbackUriPrefixList) {
		toSerialize["callbackUriPrefixList"] = o.CallbackUriPrefixList
	}
	if !IsNil(o.DefaultNotificationSubscriptions) {
		toSerialize["defaultNotificationSubscriptions"] = o.DefaultNotificationSubscriptions
	}
	if !IsNil(o.AllowedPlmns) {
		toSerialize["allowedPlmns"] = o.AllowedPlmns
	}
	if !IsNil(o.AllowedSnpns) {
		toSerialize["allowedSnpns"] = o.AllowedSnpns
	}
	if !IsNil(o.AllowedNfTypes) {
		toSerialize["allowedNfTypes"] = o.AllowedNfTypes
	}
	if !IsNil(o.AllowedNfDomains) {
		toSerialize["allowedNfDomains"] = o.AllowedNfDomains
	}
	if !IsNil(o.AllowedNssais) {
		toSerialize["allowedNssais"] = o.AllowedNssais
	}
	if !IsNil(o.AllowedOperationsPerNfType) {
		toSerialize["allowedOperationsPerNfType"] = o.AllowedOperationsPerNfType
	}
	if !IsNil(o.AllowedOperationsPerNfInstance) {
		toSerialize["allowedOperationsPerNfInstance"] = o.AllowedOperationsPerNfInstance
	}
	if !IsNil(o.AllowedOperationsPerNfInstanceOverrides) {
		toSerialize["allowedOperationsPerNfInstanceOverrides"] = o.AllowedOperationsPerNfInstanceOverrides
	}
	if !IsNil(o.AllowedScopesRuleSet) {
		toSerialize["allowedScopesRuleSet"] = o.AllowedScopesRuleSet
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Capacity) {
		toSerialize["capacity"] = o.Capacity
	}
	if !IsNil(o.Load) {
		toSerialize["load"] = o.Load
	}
	if !IsNil(o.LoadTimeStamp) {
		toSerialize["loadTimeStamp"] = o.LoadTimeStamp
	}
	if !IsNil(o.RecoveryTime) {
		toSerialize["recoveryTime"] = o.RecoveryTime
	}
	if !IsNil(o.SupportedFeatures) {
		toSerialize["supportedFeatures"] = o.SupportedFeatures
	}
	if !IsNil(o.NfServiceSetIdList) {
		toSerialize["NfServiceSetIdList"] = o.NfServiceSetIdList
	}
	if !IsNil(o.SNssais) {
		toSerialize["sNssais"] = o.SNssais
	}
	if !IsNil(o.PerPlmnSnssaiList) {
		toSerialize["perPlmnSnssaiList"] = o.PerPlmnSnssaiList
	}
	if !IsNil(o.VendorId) {
		toSerialize["vendorId"] = o.VendorId
	}
	if !IsNil(o.SupportedVendorSpecificFeatures) {
		toSerialize["supportedVendorSpecificFeatures"] = o.SupportedVendorSpecificFeatures
	}
	if !IsNil(o.Oauth2Required) {
		toSerialize["oauth2Required"] = o.Oauth2Required
	}
	if !IsNil(o.PerPlmnOauth2ReqList) {
		toSerialize["perPlmnOauth2ReqList"] = o.PerPlmnOauth2ReqList
	}
	if !IsNil(o.SelectionConditions) {
		toSerialize["selectionConditions"] = o.SelectionConditions
	}
	if !IsNil(o.CanaryRelease) {
		toSerialize["canaryRelease"] = o.CanaryRelease
	}
	if !IsNil(o.ExclusiveCanaryReleaseSelection) {
		toSerialize["exclusiveCanaryReleaseSelection"] = o.ExclusiveCanaryReleaseSelection
	}
	if !IsNil(o.SharedServiceDataId) {
		toSerialize["sharedServiceDataId"] = o.SharedServiceDataId
	}
	if !IsNil(o.ShutdownTime) {
		toSerialize["shutdownTime"] = o.ShutdownTime
	}
	if !IsNil(o.CanaryPrecedenceOverPreferred) {
		toSerialize["canaryPrecedenceOverPreferred"] = o.CanaryPrecedenceOverPreferred
	}
	return toSerialize, nil
}

func (o *NfService) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceInstanceId",
		"serviceName",
		"versions",
		"scheme",
		"nfServiceStatus",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNfService := _NfService{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNfService)

	if err != nil {
		return err
	}

	*o = NfService(varNfService)

	return err
}

type NullableNfService struct {
	value *NfService
	isSet bool
}

func (v NullableNfService) Get() *NfService {
	return v.value
}

func (v *NullableNfService) Set(val *NfService) {
	v.value = val
	v.isSet = true
}

func (v NullableNfService) IsSet() bool {
	return v.isSet
}

func (v *NullableNfService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNfService(val *NfService) *NullableNfService {
	return &NullableNfService{value: val, isSet: true}
}

func (v NullableNfService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNfService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
